# Generated by Django 6.0.7 on 2026-07-21 19:04

import common.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_category_storage_mode_product_storage_mode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Model3D",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "storage_mode",
                    models.CharField(
                        default=common.models.current_storage_mode,
                        editable=False,
                        max_length=20,
                    ),
                ),
                (
                    "glb_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="assets/glb/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["glb", "gltf"]
                            )
                        ],
                    ),
                ),
                (
                    "usdz_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="assets/usdz/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["usdz"])
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Yuklandi"),
                            ("processing", "Qayta ishlanmoqda"),
                            ("ready", "Tayyor"),
                            ("failed", "Xatolik"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "scale_width",
                    models.DecimalField(decimal_places=2, default=1, max_digits=6),
                ),
                (
                    "scale_height",
                    models.DecimalField(decimal_places=2, default=1, max_digits=6),
                ),
                (
                    "scale_depth",
                    models.DecimalField(decimal_places=2, default=1, max_digits=6),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model3d",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
