# Generated by Django 6.0.7 on 2026-07-25 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0005_alter_model3d_glb_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="model3d",
            name="texture_archive",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="assets/textures/",
                validators=[django.core.validators.FileExtensionValidator(["zip"])],
            ),
        ),
    ]
