# Generated by Django 6.0.7 on 2026-07-25 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0006_model3d_texture_archive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model3d",
            name="texture_archive",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="assets/textures/",
                validators=[
                    django.core.validators.FileExtensionValidator(["zip", "rar"])
                ],
            ),
        ),
    ]
