# Generated by Django 6.0.7 on 2026-07-25 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0007_alter_model3d_texture_archive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model3d",
            name="glb_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="assets/glb/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["glb", "gltf", "fbx", "obj", "zip", "rar"]
                    )
                ],
            ),
        ),
    ]
