# Generated by Django 6.0.7 on 2026-07-26 09:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0008_alter_model3d_glb_file"),
        ("products", "0004_product_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="model3d",
            name="variant",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model3d",
                to="products.variant",
            ),
        ),
        migrations.AlterField(
            model_name="model3d",
            name="glb_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="assets/glb/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["glb", "gltf", "fbx", "obj", "dae", "zip", "rar"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="model3d",
            name="product",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model3d",
                to="products.product",
            ),
        ),
    ]
