# Generated by Django 6.0.7 on 2026-08-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0009_model3d_variant_alter_model3d_glb_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="model3d",
            name="bbox_depth",
            field=models.DecimalField(
                blank=True, decimal_places=4, editable=False, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="model3d",
            name="bbox_height",
            field=models.DecimalField(
                blank=True, decimal_places=4, editable=False, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="model3d",
            name="bbox_width",
            field=models.DecimalField(
                blank=True, decimal_places=4, editable=False, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="model3d",
            name="shape_tag",
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
