# Generated by Django 6.0.7 on 2026-09-04 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0010_model3d_bbox_depth_model3d_bbox_height_and_more"),
        ("custom_orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="model3d",
            name="design_version",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model3d",
                to="custom_orders.designversion",
            ),
        ),
    ]
