# Generated by Django 6.0.7 on 2026-08-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0003_billofmaterial_cut_length_material_stock_unit_length_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="address",
            field=models.CharField(max_length=500),
        ),
    ]
