# Generated by Django 6.0.7 on 2026-08-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_warehouse_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehouse",
            name="branch",
        ),
    ]
