# Generated by Django 6.0.7 on 2026-08-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0006_material_min_stock_purchaseorder_purchaseorderitem_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="materialremnant",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="billofmaterial",
            name="cut_width",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="dimension_type",
            field=models.CharField(
                choices=[
                    ("none", "Oddiy (o'lchamsiz)"),
                    ("linear", "Chiziqli (uzunlik bo'yicha)"),
                    ("sheet", "Varaq (eni x bo'yi)"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="materialremnant",
            name="width",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="materialremnant",
            unique_together={("warehouse", "material", "length", "width")},
        ),
    ]
