# Generated by Django 6.0.7 on 2026-08-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_materialremnant_unique_together_and_more"),
        ("products", "0008_product_color_tag"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="billofmaterial",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="billofmaterial",
            name="part_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="billofmaterial",
            unique_together={("product", "material", "part_name")},
        ),
    ]
