# Generated by Django 6.0.7 on 2026-08-28 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_alter_billofmaterial_unique_together_and_more"),
        (
            "workflow",
            "0005_workflowstep_quantity_workflowstepinstance_quantity_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="materialmovement",
            name="workflow_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="material_movements",
                to="workflow.workflowstepinstance",
            ),
        ),
        migrations.AlterField(
            model_name="materialmovement",
            name="movement_type",
            field=models.CharField(
                choices=[("in", "Kirim"), ("out", "Chiqim"), ("return", "Qaytarish")],
                max_length=10,
            ),
        ),
    ]
