# Generated by Django 6.0.7 on 2026-09-04 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_materialmovement_workflow_instance_and_more"),
        ("orders", "0005_order_order_type_orderitem_cost_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmovement",
            name="source_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to="orders.order",
            ),
        ),
    ]
