# Generated by Django 5.2.17 on 2026-09-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_productmovement_source_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="materials/"),
        ),
    ]
