import Foundation

/// Asosiy matnlar lug'ati — 9 til, Flutter'dagi `lib/l10n/strings.dart` va
/// web'dagi `frontend/src/l10n/strings.js` bilan bir xil kalitlar/tarjimalar
/// (barcha platformalarda bir xil so'zlar ishlatiladi). Navigatsiya, kirish
/// (auth), bosh sahifa, sevimlilar, savat va mahsulot sahifasi kabi eng ko'p
/// ko'rinadigan matnlar qamrab olingan.
let appLocales: [(code: String, nativeName: String, flag: String)] = [
    ("uz", "O'zbekcha", "🇺🇿"),
    ("en", "English", "🇬🇧"),
    ("ru", "Русский", "🇷🇺"),
    ("tg", "Тоҷикӣ", "🇹🇯"),
    ("tr", "Türkçe", "🇹🇷"),
    ("ky", "Кыргызча", "🇰🇬"),
    ("kk", "Қазақша", "🇰🇿"),
    ("de", "Deutsch", "🇩🇪"),
    ("az", "Azərbaycan", "🇦🇿"),
]

let defaultLocaleCode = "uz"

private let stringsTable: [String: [String: String]] = [
    "uz": [
        "auth_google": "Google orqali kirish",
        "auth_telegram": "Telegram orqali kirish",
        "dim_title": "O'lchamlari",
        "dim_width": "Eni",
        "dim_height": "Bo'yi",
        "dim_depth": "Chuqurligi",
        "dim_volume": "Hajmi",
        "company_verified": "Tasdiqlangan firma",
        "delivery_title": "Yetkazib berish",
        "delivery_free": "Bepul",
        "delivery_days_suffix": " kun",
        "delivery_agreed": "Yetkazib berish shartlari firma bilan kelishiladi",
        "delivery_price_label": "Narxi",
        "delivery_time_label": "Muddat",
        "cart_delivery_note": "Firma bilan kelishiladi",
        "price_from_suffix": " dan",
        "update_title": "Ilovani yangilang", "update_forced_message": "Ushbu versiya endi qo‘llab-quvvatlanmaydi. Davom etish uchun VIDA Market ilovasini yangilang.", "update_available_title": "Yangi versiya mavjud", "update_button": "Yangilash", "update_later": "Keyinroq", "update_retry": "Qayta urinish", "update_recheck": "Qayta tekshirish", "update_latest_version": "Oxirgi versiya", "update_store_error": "Do‘kon havolasi ochilmadi",
        "nav_home": "Bosh sahifa", "nav_catalog": "Katalog", "nav_likes": "Sevimlilar",
        "nav_cart": "Savat", "nav_profile": "Profil",
        "auth_title": "Kirish", "auth_phone_hint": "Telefon", "auth_select_country": "Davlat",
        "auth_send_code": "Kod yuborish", "auth_phone_invalid": "Raqam noto'g'ri",
        "auth_code_hint": "Kod (6 raqam)", "auth_verify": "Kirish",
        "auth_change_number": "Raqamni o'zgartirish", "auth_sms_sent": "SMS yuborildi",
        "auth_resend": "Qayta yuborish", "auth_profile_title": "Ma'lumotlaringiz",
        "auth_first_name": "Ism", "auth_last_name": "Familiya",
        "auth_save": "Saqlash",
        "profile_language": "Til", "profile_title": "Profil", "common_logout": "Chiqish",
        "common_close": "Yopish", "common_done": "Tayyor",
        "product_out_of_stock": "Tayyori qolmagan. Buyurtma bersangiz, biroz kutishingiz mumkin.",
        "gallery_image_error": "Rasm yuklanmadi",
        "profile_delete_account_title": "Hisobni o'chirish",
        "profile_delete_account_desc": "Hisobingizni butunlay o'chirishni so'rashingiz mumkin — so'rovingiz administrator tomonidan ko'rib chiqiladi.",
        "profile_delete_account_reason_placeholder": "Nima uchun hisobingizni o'chirmoqchisiz?",
        "profile_delete_account_action": "So'rov yuborish",
        "profile_delete_account_submit": "Yuborish",
        "profile_delete_account_cancel": "Bekor qilish",
        "profile_delete_account_pending": "So'rovingiz qabul qilindi — administrator ko'rib chiqmoqda.",
        "cart_title": "Savat", "cart_empty_title": "Savat bo'sh",
        "cart_empty_subtitle": "Katalogdan mahsulot tanlang",
        "cart_total": "Jami", "cart_submit": "Buyurtma berish", "cart_submitting": "Yuborilmoqda…",
        "cart_products_section": "Mahsulotlar",
        "cart_order_success_title": "Buyurtma qabul qilindi",
        "cart_order_success_message": "Kompaniya(lar) siz bilan tez orada bog'lanadi.",
        "checkout_login_required": "Buyurtma berish uchun Profil bo'limidan tizimga kiring",
        "catalog_title": "Katalog", "catalog_search_hint": "Mahsulot yoki firma qidirish…",
        "likes_title": "Sevimlilar",
        "likes_login_title": "Sevimlilar uchun kiring",
        "likes_login_message": "Yoqqan mahsulotlaringizni saqlash uchun Profil bo'limidan tizimga kiring.",
        "likes_empty_title": "Hali sevimli mahsulot yo'q",
        "likes_empty_message": "Katalogdan yoqqan mahsulotni yurakcha bilan belgilang.",
        "home_all": "Barchasi", "home_gps_detect": "GPS orqali aniqlash",
        "home_camera": "Kamera", "home_gallery": "Galereya",
        "home_collections": "Kolleksiyalar", "home_collections_subtitle": "Har xona uchun",
        "loc_required_title": "Joylashuvga ruxsat kerak",
        "loc_required_body": "Sizga yaqin firmalar mahsulotlarini ko'rsatish uchun joylashuvingiz kerak. Ruxsat bermaguncha mahsulotlar ko'rinmaydi.",
        "loc_gps_off_title": "Joylashuv o'chiq",
        "loc_gps_off_body": "Joylashuv xizmati (GPS) o'chirilgan. Uni yoqing — shunda atrofingizdagi firmalar mahsulotlari ko'rinadi.",
        "loc_allow": "Ruxsat berish",
        "loc_open_settings": "Sozlamalarni ochish",
        "loc_retry": "Qayta urinish",
        "loc_no_firms": "Sizning atrofingizda aktiv firma yo'q",
        "loc_no_firms_hint": "Hozircha joylashuvingizga yaqin xizmat ko'rsatadigan firma topilmadi. Keyinroq qayta urinib ko'ring.",
        "home_featured": "Ommabop mahsulotlar", "home_featured_subtitle": "Eng ko'p tanlangan",
        "home_top_products": "Top tovarlar", "home_back_tooltip": "Bosh sahifaga",
        "home_all_products": "Barcha mahsulotlar", "home_nothing_found": "Hech narsa topilmadi.",
        "home_similar_suffix": " ta o'xshash mahsulot topildi",
        "home_results_suffix": " ta natija", "home_products_suffix": " ta mahsulot",
        "home_sort_popular": "Ommabop", "home_sort_price_low": "Arzon avval",
        "home_sort_price_high": "Qimmat avval", "home_sort_name_az": "Nomi (A-Z)",
        "home_filters_extra": "Qo'shimcha filtrlar", "home_filter_ar_only": "Faqat AR / 3D mavjud",
        "home_filters_title": "Filtrlar",
        "home_viloyat_title": "Viloyat", "home_viloyat_all": "Barchasi",
        "product_title": "Mahsulot", "product_variant_field_label": "Variant (material/rang)",
        "product_dim_width": "Eni (m)", "product_dim_height": "Bo'yi (m)",
        "product_dim_depth": "Chuquri (m)", "product_qty_label": "Soni",
        "product_approx_price": "Taxminiy narx", "product_add_to_cart": "Savatga qo'shish",
        "product_share_suffix": "\nFurniture Platform ilovasida ko'ring.",
        "product_try_ar": "AR'da sinash",
        "product_3d_ios_note": "3D model mavjud (AR uchun iOS'da USDZ kerak)",
        "product_added_alert_title": "Savatga qo'shildi",
        "shop_title_fallback": "Do'kon", "shop_view_on_map": "Xaritada ko'rish",
        "shop_products": "Mahsulotlar", "shop_no_products": "Hozircha mahsulotlar yo'q",
        "shop_reviews_prefix": "Mijoz baholari (", "shop_reviews_suffix": ")",
        "shop_no_reviews": "Hali baho yo'q", "shop_anonymous_customer": "Mijoz",
        "shop_leave_review": "Baho qoldirish", "shop_comment_label": "Izoh (ixtiyoriy)",
        "shop_review_thanks": "Rahmat! Bahoyingiz saqlandi.",
        "shop_review_locked": "Faqat shu firmadan yakunlangan buyurtmangiz bo'lsa baho qoldira olasiz.",
    ],
    "en": [
        "Mahsulot": "Product",
        "Yetkazish ma'lumotlari": "Delivery details",
        "Telefon (+998…)": "Phone (+998…)",
        "Manzil": "Address",
        "Izoh (ixtiyoriy)": "Note (optional)",
        "Buyurtmani tasdiqlash": "Confirm order",
        "Buyurtma berish": "Place order",
        "Bekor": "Cancel",
        "Buyurtma qabul qilindi": "Order received",
        "Kompaniya siz bilan tez orada bog'lanadi.": "The company will contact you soon.",
        "Buyurtma berishdan oldin telefon raqamingizni SMS-kod bilan tasdiqlashingiz kerak.": "Before ordering, you need to verify your phone number with an SMS code.",
        "Telefonni tasdiqlash": "Verify phone",
        "MINIMAL VA FUNKSIONAL": "MINIMAL AND FUNCTIONAL",
        "Uyingizga\nqulaylik va hashamat": "Comfort and luxury\nfor your home",
        "O'zbekistonning eng yaxshi mebel ustalari.\nO'lchamingizga mos dizayn, uyingizga yetkazib berish.": "Uzbekistan's best furniture makers.\nDesign that fits your size, delivered to your home.",
        "Internet aloqasi yo'q": "No internet connection",
        "Hali xabarnoma yo'q.": "No notifications yet.",
        "Xabarnomalar": "Notifications",
        "Hammasini o'qilgan qilish": "Mark all as read",
        "Hali loyiha yo'q": "No projects yet",
        "Mahsulotlarni AR'da ko'rsatish uchun avval loyiha yarating.": "Create a project first to show products in AR.",
        "Loyihalarim": "My projects",
        "Yangi loyiha": "New project",
        "Loyiha nomi": "Project name",
        "Yaratish": "Create",
        "Hali mahsulot qo'shilmagan": "No products added yet",
        "+ Mahsulot qo'shish": "+ Add product",
        "Rang: joylashtirishda tanlanadi": "Color: chosen when placing",
        "3D modeli tayyor mahsulot yo'q": "No products with a ready 3D model",
        "Mahsulot qo'shish": "Add product",
        "Rangni tanlang": "Choose a color",
        "Davom etish": "Continue",
        "Bog'langan hisoblar": "Linked accounts",
        "Bog'lash": "Link",
        "Ko'rinish rejimi": "View mode",
        "Rejim": "Mode",
        "Xaridor": "Customer",
        "Ish takliflari": "Job offers",
        "Qabul qilish": "Accept",
        "Rad etish": "Decline",
        "Ish tarixi (karyera)": "Work history (career)",
        "hozir": "now",
        "So'nggi buyurtmalar": "Recent orders",
        "Hali buyurtma yo'q": "No orders yet",
        "va yana %d ta buyurtma": "and %d more orders",
        "Ishlab chiqarish jarayoni": "Production progress",
        "Ijrochi: %@": "Assignee: %@",
        "Ishlab chiqarish: %d%%": "Production: %d%%",
        "Hozir: %@": "Now: %@",
        "auth_google": "Sign in with Google",
        "auth_telegram": "Sign in with Telegram",
        "dim_title": "Dimensions",
        "dim_width": "Width",
        "dim_height": "Height",
        "dim_depth": "Depth",
        "dim_volume": "Volume",
        "company_verified": "Verified company",
        "delivery_title": "Delivery",
        "delivery_free": "Free",
        "delivery_days_suffix": " days",
        "delivery_agreed": "Delivery terms are agreed with the company",
        "delivery_price_label": "Price",
        "delivery_time_label": "Time",
        "cart_delivery_note": "Agreed with the company",
        "price_from_suffix": " from",
        "update_title": "Update the app", "update_forced_message": "This version is no longer supported. Please update VIDA Market to continue.", "update_available_title": "New version available", "update_button": "Update", "update_later": "Later", "update_retry": "Retry", "update_recheck": "Check again", "update_latest_version": "Latest version", "update_store_error": "Could not open the store link",
        "nav_home": "Home", "nav_catalog": "Catalog", "nav_likes": "Favorites",
        "nav_cart": "Cart", "nav_profile": "Profile",
        "auth_title": "Sign in", "auth_phone_hint": "Phone", "auth_select_country": "Country",
        "auth_send_code": "Send code", "auth_phone_invalid": "Invalid number",
        "auth_code_hint": "Code (6 digits)", "auth_verify": "Sign in",
        "auth_change_number": "Change number", "auth_sms_sent": "SMS sent",
        "auth_resend": "Resend", "auth_profile_title": "Your details",
        "auth_first_name": "First name", "auth_last_name": "Last name",
        "auth_save": "Save",
        "profile_language": "Language", "profile_title": "Profile", "common_logout": "Log out",
        "common_close": "Close", "common_done": "Done",
        "product_out_of_stock": "Not in stock right now. If you order, you may need to wait a little.",
        "gallery_image_error": "Image failed to load",
        "profile_delete_account_title": "Delete account",
        "profile_delete_account_desc": "You can request permanent deletion of your account — your request will be reviewed by an administrator.",
        "profile_delete_account_reason_placeholder": "Why do you want to delete your account?",
        "profile_delete_account_action": "Send request",
        "profile_delete_account_submit": "Submit",
        "profile_delete_account_cancel": "Cancel",
        "profile_delete_account_pending": "Your request has been received — an administrator is reviewing it.",
        "cart_title": "Cart", "cart_empty_title": "Cart is empty",
        "cart_empty_subtitle": "Pick something from the catalog",
        "cart_total": "Total", "cart_submit": "Place order", "cart_submitting": "Submitting…",
        "cart_products_section": "Products",
        "cart_order_success_title": "Order received",
        "cart_order_success_message": "The company(ies) will contact you soon.",
        "checkout_login_required": "Sign in from the Profile tab to place an order",
        "catalog_title": "Catalog", "catalog_search_hint": "Search product or company…",
        "likes_title": "Favorites",
        "likes_login_title": "Sign in for favorites",
        "likes_login_message": "Sign in from the Profile tab to save products you like.",
        "likes_empty_title": "No favorites yet",
        "likes_empty_message": "Tap the heart on a product in the catalog to save it here.",
        "home_all": "All", "home_gps_detect": "Detect via GPS",
        "home_camera": "Camera", "home_gallery": "Gallery",
        "home_collections": "Collections", "home_collections_subtitle": "For every room",
        "loc_required_title": "Location permission needed",
        "loc_required_body": "We need your location to show products from firms near you. Products stay hidden until you allow it.",
        "loc_gps_off_title": "Location is off",
        "loc_gps_off_body": "Location services (GPS) are turned off. Turn them on to see products from firms around you.",
        "loc_allow": "Allow",
        "loc_open_settings": "Open settings",
        "loc_retry": "Try again",
        "loc_no_firms": "No active firm near you",
        "loc_no_firms_hint": "No firm currently serves your location. Please try again later.",
        "home_featured": "Popular products", "home_featured_subtitle": "Most chosen",
        "home_top_products": "Top products", "home_back_tooltip": "Back to home",
        "home_all_products": "All products", "home_nothing_found": "Nothing found.",
        "home_similar_suffix": " similar products found",
        "home_results_suffix": " results", "home_products_suffix": " products",
        "home_sort_popular": "Popular", "home_sort_price_low": "Price: low to high",
        "home_sort_price_high": "Price: high to low", "home_sort_name_az": "Name (A-Z)",
        "home_filters_extra": "Additional filters", "home_filter_ar_only": "AR / 3D available only",
        "home_filters_title": "Filters",
        "home_viloyat_title": "Region", "home_viloyat_all": "All",
        "product_title": "Product", "product_variant_field_label": "Variant (material/color)",
        "product_dim_width": "Width (m)", "product_dim_height": "Height (m)",
        "product_dim_depth": "Depth (m)", "product_qty_label": "Quantity",
        "product_approx_price": "Estimated price", "product_add_to_cart": "Add to cart",
        "product_share_suffix": "\nSee it in the Furniture Platform app.",
        "product_try_ar": "Try in AR",
        "product_3d_ios_note": "3D model available (AR on iOS requires USDZ)",
        "product_added_alert_title": "Added to cart",
        "shop_title_fallback": "Shop", "shop_view_on_map": "View on map",
        "shop_products": "Products", "shop_no_products": "No products yet",
        "shop_reviews_prefix": "Customer reviews (", "shop_reviews_suffix": ")",
        "shop_no_reviews": "No reviews yet", "shop_anonymous_customer": "Customer",
        "shop_leave_review": "Leave a review", "shop_comment_label": "Comment (optional)",
        "shop_review_thanks": "Thanks! Your review has been saved.",
        "shop_review_locked": "You can leave a review only after completing an order with this company.",
    ],
    "ru": [
        "Mahsulot": "Товар",
        "Yetkazish ma'lumotlari": "Данные доставки",
        "Telefon (+998…)": "Телефон (+998…)",
        "Manzil": "Адрес",
        "Izoh (ixtiyoriy)": "Комментарий (необязательно)",
        "Buyurtmani tasdiqlash": "Подтвердить заказ",
        "Buyurtma berish": "Оформить заказ",
        "Bekor": "Отмена",
        "Buyurtma qabul qilindi": "Заказ принят",
        "Kompaniya siz bilan tez orada bog'lanadi.": "Компания свяжется с вами в ближайшее время.",
        "Buyurtma berishdan oldin telefon raqamingizni SMS-kod bilan tasdiqlashingiz kerak.": "Перед оформлением заказа подтвердите номер телефона SMS-кодом.",
        "Telefonni tasdiqlash": "Подтверждение телефона",
        "MINIMAL VA FUNKSIONAL": "МИНИМАЛИЗМ И ФУНКЦИОНАЛЬНОСТЬ",
        "Uyingizga\nqulaylik va hashamat": "Уют и роскошь\nдля вашего дома",
        "O'zbekistonning eng yaxshi mebel ustalari.\nO'lchamingizga mos dizayn, uyingizga yetkazib berish.": "Лучшие мебельные мастера Узбекистана.\nДизайн под ваши размеры, доставка домой.",
        "Internet aloqasi yo'q": "Нет подключения к интернету",
        "Hali xabarnoma yo'q.": "Уведомлений пока нет.",
        "Xabarnomalar": "Уведомления",
        "Hammasini o'qilgan qilish": "Отметить все как прочитанные",
        "Hali loyiha yo'q": "Проектов пока нет",
        "Mahsulotlarni AR'da ko'rsatish uchun avval loyiha yarating.": "Сначала создайте проект, чтобы показывать товары в AR.",
        "Loyihalarim": "Мои проекты",
        "Yangi loyiha": "Новый проект",
        "Loyiha nomi": "Название проекта",
        "Yaratish": "Создать",
        "Hali mahsulot qo'shilmagan": "Товары ещё не добавлены",
        "+ Mahsulot qo'shish": "+ Добавить товар",
        "Rang: joylashtirishda tanlanadi": "Цвет: выбирается при размещении",
        "3D modeli tayyor mahsulot yo'q": "Нет товаров с готовой 3D-моделью",
        "Mahsulot qo'shish": "Добавить товар",
        "Rangni tanlang": "Выберите цвет",
        "Davom etish": "Продолжить",
        "Bog'langan hisoblar": "Связанные аккаунты",
        "Bog'lash": "Привязать",
        "Ko'rinish rejimi": "Режим просмотра",
        "Rejim": "Режим",
        "Xaridor": "Покупатель",
        "Ish takliflari": "Предложения работы",
        "Qabul qilish": "Принять",
        "Rad etish": "Отклонить",
        "Ish tarixi (karyera)": "История работы (карьера)",
        "hozir": "сейчас",
        "So'nggi buyurtmalar": "Последние заказы",
        "Hali buyurtma yo'q": "Заказов пока нет",
        "va yana %d ta buyurtma": "и ещё %d заказов",
        "Ishlab chiqarish jarayoni": "Ход производства",
        "Ijrochi: %@": "Исполнитель: %@",
        "Ishlab chiqarish: %d%%": "Производство: %d%%",
        "Hozir: %@": "Сейчас: %@",
        "auth_google": "Войти через Google",
        "auth_telegram": "Войти через Telegram",
        "dim_title": "Размеры",
        "dim_width": "Ширина",
        "dim_height": "Высота",
        "dim_depth": "Глубина",
        "dim_volume": "Объём",
        "company_verified": "Проверенная фирма",
        "delivery_title": "Доставка",
        "delivery_free": "Бесплатно",
        "delivery_days_suffix": " дн.",
        "delivery_agreed": "Условия доставки согласуются с фирмой",
        "delivery_price_label": "Стоимость",
        "delivery_time_label": "Срок",
        "cart_delivery_note": "Согласуется с фирмой",
        "price_from_suffix": " от",
        "update_title": "Обновите приложение", "update_forced_message": "Эта версия больше не поддерживается. Обновите VIDA Market, чтобы продолжить.", "update_available_title": "Доступна новая версия", "update_button": "Обновить", "update_later": "Позже", "update_retry": "Повторить", "update_recheck": "Проверить снова", "update_latest_version": "Последняя версия", "update_store_error": "Не удалось открыть ссылку магазина",
        "nav_home": "Главная", "nav_catalog": "Каталог", "nav_likes": "Избранное",
        "nav_cart": "Корзина", "nav_profile": "Профиль",
        "auth_title": "Вход", "auth_phone_hint": "Телефон", "auth_select_country": "Страна",
        "auth_send_code": "Отправить код", "auth_phone_invalid": "Неверный номер",
        "auth_code_hint": "Код (6 цифр)", "auth_verify": "Войти",
        "auth_change_number": "Изменить номер", "auth_sms_sent": "SMS отправлено",
        "auth_resend": "Отправить снова", "auth_profile_title": "Ваши данные",
        "auth_first_name": "Имя", "auth_last_name": "Фамилия",
        "auth_save": "Сохранить",
        "profile_language": "Язык", "profile_title": "Профиль", "common_logout": "Выйти",
        "common_close": "Закрыть", "common_done": "Готово",
        "product_out_of_stock": "Готового товара нет в наличии. Если оформите заказ, придётся немного подождать.",
        "gallery_image_error": "Не удалось загрузить фото",
        "profile_delete_account_title": "Удалить аккаунт",
        "profile_delete_account_desc": "Вы можете запросить полное удаление аккаунта — запрос будет рассмотрен администратором.",
        "profile_delete_account_reason_placeholder": "Почему вы хотите удалить аккаунт?",
        "profile_delete_account_action": "Отправить запрос",
        "profile_delete_account_submit": "Отправить",
        "profile_delete_account_cancel": "Отмена",
        "profile_delete_account_pending": "Ваш запрос принят — администратор рассматривает его.",
        "cart_title": "Корзина", "cart_empty_title": "Корзина пуста",
        "cart_empty_subtitle": "Выберите товар в каталоге",
        "cart_total": "Итого", "cart_submit": "Оформить заказ", "cart_submitting": "Отправка…",
        "cart_products_section": "Товары",
        "cart_order_success_title": "Заказ принят",
        "cart_order_success_message": "Компания(и) свяжется с вами в ближайшее время.",
        "checkout_login_required": "Войдите в разделе Профиль, чтобы оформить заказ",
        "catalog_title": "Каталог", "catalog_search_hint": "Поиск товара или компании…",
        "likes_title": "Избранное",
        "likes_login_title": "Войдите для избранного",
        "likes_login_message": "Войдите в разделе Профиль, чтобы сохранять понравившиеся товары.",
        "likes_empty_title": "Пока нет избранных товаров",
        "likes_empty_message": "Отметьте понравившийся товар сердечком в каталоге.",
        "home_all": "Все", "home_gps_detect": "Определить по GPS",
        "home_camera": "Камера", "home_gallery": "Галерея",
        "home_collections": "Коллекции", "home_collections_subtitle": "Для каждой комнаты",
        "loc_required_title": "Нужен доступ к местоположению",
        "loc_required_body": "Чтобы показать товары ближайших фирм, нужно ваше местоположение. Пока вы не разрешите, товары не отображаются.",
        "loc_gps_off_title": "Геолокация выключена",
        "loc_gps_off_body": "Службы геолокации (GPS) отключены. Включите их, чтобы увидеть товары фирм рядом.",
        "loc_allow": "Разрешить",
        "loc_open_settings": "Открыть настройки",
        "loc_retry": "Повторить",
        "loc_no_firms": "Рядом с вами нет активных фирм",
        "loc_no_firms_hint": "Сейчас нет фирм, обслуживающих ваше местоположение. Попробуйте позже.",
        "home_featured": "Популярные товары", "home_featured_subtitle": "Самые выбираемые",
        "home_top_products": "Топ товары", "home_back_tooltip": "На главную",
        "home_all_products": "Все товары", "home_nothing_found": "Ничего не найдено.",
        "home_similar_suffix": " похожих товаров найдено",
        "home_results_suffix": " результатов", "home_products_suffix": " товаров",
        "home_sort_popular": "Популярное", "home_sort_price_low": "Сначала дешёвые",
        "home_sort_price_high": "Сначала дорогие", "home_sort_name_az": "Название (А-Я)",
        "home_filters_extra": "Дополнительные фильтры", "home_filter_ar_only": "Только с AR / 3D",
        "home_filters_title": "Фильтры",
        "home_viloyat_title": "Область", "home_viloyat_all": "Все",
        "product_title": "Товар", "product_variant_field_label": "Вариант (материал/цвет)",
        "product_dim_width": "Ширина (м)", "product_dim_height": "Высота (м)",
        "product_dim_depth": "Глубина (м)", "product_qty_label": "Количество",
        "product_approx_price": "Примерная цена", "product_add_to_cart": "В корзину",
        "product_share_suffix": "\nПосмотрите в приложении Furniture Platform.",
        "product_try_ar": "Примерить в AR",
        "product_3d_ios_note": "3D-модель доступна (для AR на iOS нужен USDZ)",
        "product_added_alert_title": "Добавлено в корзину",
        "shop_title_fallback": "Магазин", "shop_view_on_map": "Смотреть на карте",
        "shop_products": "Товары", "shop_no_products": "Пока нет товаров",
        "shop_reviews_prefix": "Отзывы клиентов (", "shop_reviews_suffix": ")",
        "shop_no_reviews": "Отзывов пока нет", "shop_anonymous_customer": "Клиент",
        "shop_leave_review": "Оставить отзыв", "shop_comment_label": "Комментарий (необязательно)",
        "shop_review_thanks": "Спасибо! Ваш отзыв сохранён.",
        "shop_review_locked": "Оставить отзыв можно только после завершённого заказа у этой компании.",
    ],
    "tg": [
        "Mahsulot": "Маҳсулот",
        "Yetkazish ma'lumotlari": "Маълумоти расонидан",
        "Telefon (+998…)": "Телефон (+998…)",
        "Manzil": "Суроға",
        "Izoh (ixtiyoriy)": "Изоҳ (ихтиёрӣ)",
        "Buyurtmani tasdiqlash": "Тасдиқи фармоиш",
        "Buyurtma berish": "Фармоиш додан",
        "Bekor": "Бекор",
        "Buyurtma qabul qilindi": "Фармоиш қабул шуд",
        "Kompaniya siz bilan tez orada bog'lanadi.": "Ширкат ба зудӣ бо шумо тамос мегирад.",
        "Buyurtma berishdan oldin telefon raqamingizni SMS-kod bilan tasdiqlashingiz kerak.": "Пеш аз фармоиш рақами телефони худро бо коди SMS тасдиқ кунед.",
        "Telefonni tasdiqlash": "Тасдиқи телефон",
        "MINIMAL VA FUNKSIONAL": "МИНИМАЛӢ ВА ФУНКСИОНАЛӢ",
        "Uyingizga\nqulaylik va hashamat": "Роҳат ва шукӯҳ\nба хонаи шумо",
        "O'zbekistonning eng yaxshi mebel ustalari.\nO'lchamingizga mos dizayn, uyingizga yetkazib berish.": "Беҳтарин усто­ҳои мебели Ӯзбекистон.\nДизайн мувофиқи андозаи шумо, расонидан ба хона.",
        "Internet aloqasi yo'q": "Алоқаи интернет нест",
        "Hali xabarnoma yo'q.": "Ҳанӯз огоҳинома нест.",
        "Xabarnomalar": "Огоҳиномаҳо",
        "Hammasini o'qilgan qilish": "Ҳамаро хондашуда қайд кардан",
        "Hali loyiha yo'q": "Ҳанӯз лоиҳа нест",
        "Mahsulotlarni AR'da ko'rsatish uchun avval loyiha yarating.": "Барои намоиши маҳсулот дар AR аввал лоиҳа созед.",
        "Loyihalarim": "Лоиҳаҳои ман",
        "Yangi loyiha": "Лоиҳаи нав",
        "Loyiha nomi": "Номи лоиҳа",
        "Yaratish": "Эҷод кардан",
        "Hali mahsulot qo'shilmagan": "Ҳанӯз маҳсулот илова нашудааст",
        "+ Mahsulot qo'shish": "+ Илова кардани маҳсулот",
        "Rang: joylashtirishda tanlanadi": "Ранг: ҳангоми ҷойгиркунӣ интихоб мешавад",
        "3D modeli tayyor mahsulot yo'q": "Маҳсулот бо модели 3D-и омода нест",
        "Mahsulot qo'shish": "Илова кардани маҳсулот",
        "Rangni tanlang": "Рангро интихоб кунед",
        "Davom etish": "Давом додан",
        "Bog'langan hisoblar": "Ҳисобҳои пайваст",
        "Bog'lash": "Пайваст кардан",
        "Ko'rinish rejimi": "Реҷаи намоиш",
        "Rejim": "Реҷа",
        "Xaridor": "Харидор",
        "Ish takliflari": "Пешниҳодҳои кор",
        "Qabul qilish": "Қабул кардан",
        "Rad etish": "Рад кардан",
        "Ish tarixi (karyera)": "Таърихи кор (касб)",
        "hozir": "ҳоло",
        "So'nggi buyurtmalar": "Фармоишҳои охирин",
        "Hali buyurtma yo'q": "Ҳанӯз фармоиш нест",
        "va yana %d ta buyurtma": "ва боз %d фармоиш",
        "Ishlab chiqarish jarayoni": "Ҷараёни истеҳсол",
        "Ijrochi: %@": "Иҷрокунанда: %@",
        "Ishlab chiqarish: %d%%": "Истеҳсол: %d%%",
        "Hozir: %@": "Ҳоло: %@",
        "auth_google": "Вуруд бо Google",
        "auth_telegram": "Вуруд бо Telegram",
        "dim_title": "Андозаҳо",
        "dim_width": "Паҳно",
        "dim_height": "Баландӣ",
        "dim_depth": "Чуқурӣ",
        "dim_volume": "Ҳаҷм",
        "company_verified": "Ширкати тасдиқшуда",
        "delivery_title": "Расонидан",
        "delivery_free": "Ройгон",
        "delivery_days_suffix": " рӯз",
        "delivery_agreed": "Шартҳои расонидан бо ширкат мувофиқа карда мешавад",
        "delivery_price_label": "Нарх",
        "delivery_time_label": "Мӯҳлат",
        "cart_delivery_note": "Бо ширкат мувофиқа карда мешавад",
        "price_from_suffix": " аз",
        "update_title": "Барномаро нав кунед", "update_forced_message": "Ин нусха дигар дастгирӣ намешавад. Барои идома VIDA Market-ро нав кунед.", "update_available_title": "Версияи нав мавҷуд аст", "update_button": "Нав кардан", "update_later": "Баъдтар", "update_retry": "Такрор", "update_recheck": "Аз нав санҷидан", "update_latest_version": "Версияи охирин", "update_store_error": "Пайванди мағоза кушода нашуд",
        "nav_home": "Саҳифаи асосӣ", "nav_catalog": "Каталог", "nav_likes": "Дӯстдоштаҳо",
        "nav_cart": "Сабад", "nav_profile": "Профил",
        "auth_title": "Воридшавӣ", "auth_phone_hint": "Телефон", "auth_select_country": "Кишвар",
        "auth_send_code": "Фиристодани код", "auth_phone_invalid": "Рақами нодуруст",
        "auth_code_hint": "Код (6 рақам)", "auth_verify": "Ворид шудан",
        "auth_change_number": "Тағйири рақам", "auth_sms_sent": "SMS фиристода шуд",
        "auth_resend": "Дубора фиристодан", "auth_profile_title": "Маълумоти шумо",
        "auth_first_name": "Ном", "auth_last_name": "Насаб",
        "auth_save": "Нигоҳ доштан",
        "profile_language": "Забон", "profile_title": "Профил", "common_logout": "Баромадан",
        "common_close": "Пӯшидан", "common_done": "Тайёр",
        "product_out_of_stock": "Маҳсули тайёр дар анбор нест. Агар фармоиш диҳед, каме интизор шудан мумкин аст.",
        "gallery_image_error": "Акс бор нашуд",
        "profile_delete_account_title": "Ҳисобро нест кардан",
        "profile_delete_account_desc": "Шумо метавонед дархости нест кардани пурраи ҳисобро фиристед — дархости шумо аз ҷониби маъмур баррасӣ мешавад.",
        "profile_delete_account_reason_placeholder": "Чаро мехоҳед ҳисобатонро нест кунед?",
        "profile_delete_account_action": "Фиристодани дархост",
        "profile_delete_account_submit": "Фиристодан",
        "profile_delete_account_cancel": "Бекор кардан",
        "profile_delete_account_pending": "Дархости шумо қабул шуд — маъмур онро баррасӣ мекунад.",
        "cart_title": "Сабад", "cart_empty_title": "Сабад холист",
        "cart_empty_subtitle": "Аз каталог маҳсулот интихоб кунед",
        "cart_total": "Ҳамагӣ", "cart_submit": "Фармоиш додан", "cart_submitting": "Фиристода истодааст…",
        "cart_products_section": "Маҳсулот",
        "cart_order_success_title": "Фармоиш қабул шуд",
        "cart_order_success_message": "Ширкат(ҳо) ба зудӣ бо шумо тамос мегирад.",
        "checkout_login_required": "Барои фармоиш додан аз бахши Профил ворид шавед",
        "catalog_title": "Каталог", "catalog_search_hint": "Маҳсулот ё ширкатро ҷустуҷӯ кунед…",
        "likes_title": "Дӯстдоштаҳо",
        "likes_login_title": "Барои дӯстдоштаҳо ворид шавед",
        "likes_login_message": "Барои нигоҳ доштани маҳсулоти писандидаатон аз бахши Профил ворид шавед.",
        "likes_empty_title": "Ҳанӯз маҳсулоти дӯстдошта нест",
        "likes_empty_message": "Маҳсулоти писандидаро дар каталог бо дил қайд кунед.",
        "home_all": "Ҳама", "home_gps_detect": "Тавассути GPS муайян кардан",
        "home_camera": "Камера", "home_gallery": "Галерея",
        "home_collections": "Маҷмӯаҳо", "home_collections_subtitle": "Барои ҳар хона",
        "loc_required_title": "Иҷозати ҷойгиршавӣ лозим аст",
        "loc_required_body": "Барои нишон додани маҳсулоти ширкатҳои наздик ҷойгиршавии шумо лозим аст. То иҷозат надиҳед, маҳсулот намоён намешавад.",
        "loc_gps_off_title": "Ҷойгиршавӣ хомӯш аст",
        "loc_gps_off_body": "Хидмати ҷойгиршавӣ (GPS) хомӯш аст. Онро фаъол кунед.",
        "loc_allow": "Иҷозат додан",
        "loc_open_settings": "Кушодани танзимот",
        "loc_retry": "Аз нав кӯшиш кардан",
        "loc_no_firms": "Дар атрофи шумо ширкати фаъол нест",
        "loc_no_firms_hint": "Айни замон ширкате, ки ба ҷойгиршавии шумо хидмат расонад, ёфт нашуд. Баъдтар кӯшиш кунед.",
        "home_featured": "Маҳсулоти маъмул", "home_featured_subtitle": "Бештарин интихобшуда",
        "home_top_products": "Маҳсулоти беҳтарин", "home_back_tooltip": "Ба саҳифаи асосӣ",
        "home_all_products": "Ҳамаи маҳсулот", "home_nothing_found": "Чизе ёфт нашуд.",
        "home_similar_suffix": " маҳсулоти монанд ёфт шуд",
        "home_results_suffix": " натиҷа", "home_products_suffix": " маҳсулот",
        "home_sort_popular": "Маъмул", "home_sort_price_low": "Аввал арзон",
        "home_sort_price_high": "Аввал гарон", "home_sort_name_az": "Ном (А-Я)",
        "home_filters_extra": "Филтрҳои иловагӣ", "home_filter_ar_only": "Танҳо бо AR / 3D",
        "home_filters_title": "Филтрҳо",
        "home_viloyat_title": "Вилоят", "home_viloyat_all": "Ҳама",
        "product_title": "Маҳсулот", "product_variant_field_label": "Вариант (материал/ранг)",
        "product_dim_width": "Паҳно (м)", "product_dim_height": "Баландӣ (м)",
        "product_dim_depth": "Чуқурӣ (м)", "product_qty_label": "Миқдор",
        "product_approx_price": "Нархи тахминӣ", "product_add_to_cart": "Ба сабад илова кардан",
        "product_share_suffix": "\nДар барномаи Furniture Platform бинед.",
        "product_try_ar": "Дар AR санҷидан",
        "product_3d_ios_note": "Модели 3D мавҷуд аст (барои AR дар iOS USDZ лозим аст)",
        "product_added_alert_title": "Ба сабад илова шуд",
        "shop_title_fallback": "Дӯкон", "shop_view_on_map": "Дар харита дидан",
        "shop_products": "Маҳсулотҳо", "shop_no_products": "Ҳоло маҳсулот нест",
        "shop_reviews_prefix": "Баҳои мизоҷон (", "shop_reviews_suffix": ")",
        "shop_no_reviews": "Ҳанӯз баҳо нест", "shop_anonymous_customer": "Мизоҷ",
        "shop_leave_review": "Баҳо гузоштан", "shop_comment_label": "Изҳор (ихтиёрӣ)",
        "shop_review_thanks": "Ташаккур! Баҳои шумо нигоҳ дошта шуд.",
        "shop_review_locked": "Шумо танҳо пас аз фармоиши анҷомёфта аз ин ширкат метавонед баҳо гузоред.",
    ],
    "tr": [
        "Mahsulot": "Ürün",
        "Yetkazish ma'lumotlari": "Teslimat bilgileri",
        "Telefon (+998…)": "Telefon (+998…)",
        "Manzil": "Adres",
        "Izoh (ixtiyoriy)": "Not (isteğe bağlı)",
        "Buyurtmani tasdiqlash": "Siparişi onayla",
        "Buyurtma berish": "Sipariş ver",
        "Bekor": "İptal",
        "Buyurtma qabul qilindi": "Sipariş alındı",
        "Kompaniya siz bilan tez orada bog'lanadi.": "Firma sizinle kısa süre içinde iletişime geçecek.",
        "Buyurtma berishdan oldin telefon raqamingizni SMS-kod bilan tasdiqlashingiz kerak.": "Sipariş vermeden önce telefon numaranızı SMS kodu ile doğrulamanız gerekir.",
        "Telefonni tasdiqlash": "Telefonu doğrula",
        "MINIMAL VA FUNKSIONAL": "MİNİMAL VE FONKSİYONEL",
        "Uyingizga\nqulaylik va hashamat": "Evinize\nkonfor ve lüks",
        "O'zbekistonning eng yaxshi mebel ustalari.\nO'lchamingizga mos dizayn, uyingizga yetkazib berish.": "Özbekistan'ın en iyi mobilya ustaları.\nÖlçünüze uygun tasarım, evinize teslimat.",
        "Internet aloqasi yo'q": "İnternet bağlantısı yok",
        "Hali xabarnoma yo'q.": "Henüz bildirim yok.",
        "Xabarnomalar": "Bildirimler",
        "Hammasini o'qilgan qilish": "Tümünü okundu işaretle",
        "Hali loyiha yo'q": "Henüz proje yok",
        "Mahsulotlarni AR'da ko'rsatish uchun avval loyiha yarating.": "Ürünleri AR'da göstermek için önce bir proje oluşturun.",
        "Loyihalarim": "Projelerim",
        "Yangi loyiha": "Yeni proje",
        "Loyiha nomi": "Proje adı",
        "Yaratish": "Oluştur",
        "Hali mahsulot qo'shilmagan": "Henüz ürün eklenmedi",
        "+ Mahsulot qo'shish": "+ Ürün ekle",
        "Rang: joylashtirishda tanlanadi": "Renk: yerleştirirken seçilir",
        "3D modeli tayyor mahsulot yo'q": "Hazır 3D modeli olan ürün yok",
        "Mahsulot qo'shish": "Ürün ekle",
        "Rangni tanlang": "Rengi seçin",
        "Davom etish": "Devam et",
        "Bog'langan hisoblar": "Bağlı hesaplar",
        "Bog'lash": "Bağla",
        "Ko'rinish rejimi": "Görünüm modu",
        "Rejim": "Mod",
        "Xaridor": "Müşteri",
        "Ish takliflari": "İş teklifleri",
        "Qabul qilish": "Kabul et",
        "Rad etish": "Reddet",
        "Ish tarixi (karyera)": "İş geçmişi (kariyer)",
        "hozir": "şimdi",
        "So'nggi buyurtmalar": "Son siparişler",
        "Hali buyurtma yo'q": "Henüz sipariş yok",
        "va yana %d ta buyurtma": "ve %d sipariş daha",
        "Ishlab chiqarish jarayoni": "Üretim süreci",
        "Ijrochi: %@": "Sorumlu: %@",
        "Ishlab chiqarish: %d%%": "Üretim: %d%%",
        "Hozir: %@": "Şimdi: %@",
        "auth_google": "Google ile giriş yap",
        "auth_telegram": "Telegram ile giriş yap",
        "dim_title": "Boyutlar",
        "dim_width": "Genişlik",
        "dim_height": "Yükseklik",
        "dim_depth": "Derinlik",
        "dim_volume": "Hacim",
        "company_verified": "Doğrulanmış firma",
        "delivery_title": "Teslimat",
        "delivery_free": "Ücretsiz",
        "delivery_days_suffix": " gün",
        "delivery_agreed": "Teslimat koşulları firma ile netleştirilir",
        "delivery_price_label": "Ücret",
        "delivery_time_label": "Süre",
        "cart_delivery_note": "Firma ile netleştirilir",
        "price_from_suffix": " itibaren",
        "update_title": "Uygulamayı güncelleyin", "update_forced_message": "Bu sürüm artık desteklenmiyor. Devam etmek için VIDA Market'i güncelleyin.", "update_available_title": "Yeni sürüm mevcut", "update_button": "Güncelle", "update_later": "Sonra", "update_retry": "Tekrar dene", "update_recheck": "Tekrar kontrol et", "update_latest_version": "Son sürüm", "update_store_error": "Mağaza bağlantısı açılamadı",
        "nav_home": "Ana sayfa", "nav_catalog": "Katalog", "nav_likes": "Favoriler",
        "nav_cart": "Sepet", "nav_profile": "Profil",
        "auth_title": "Giriş yap", "auth_phone_hint": "Telefon", "auth_select_country": "Ülke",
        "auth_send_code": "Kodu gönder", "auth_phone_invalid": "Geçersiz numara",
        "auth_code_hint": "Kod (6 haneli)", "auth_verify": "Giriş yap",
        "auth_change_number": "Numarayı değiştir", "auth_sms_sent": "SMS gönderildi",
        "auth_resend": "Tekrar gönder", "auth_profile_title": "Bilgileriniz",
        "auth_first_name": "Ad", "auth_last_name": "Soyad",
        "auth_save": "Kaydet",
        "profile_language": "Dil", "profile_title": "Profil", "common_logout": "Çıkış yap",
        "common_close": "Kapat", "common_done": "Tamam",
        "product_out_of_stock": "Hazır ürün kalmadı. Sipariş verirseniz biraz beklemeniz gerekebilir.",
        "gallery_image_error": "Resim yüklenemedi",
        "profile_delete_account_title": "Hesabı sil",
        "profile_delete_account_desc": "Hesabınızın tamamen silinmesini talep edebilirsiniz — talebiniz yönetici tarafından incelenecek.",
        "profile_delete_account_reason_placeholder": "Hesabınızı neden silmek istiyorsunuz?",
        "profile_delete_account_action": "Talep gönder",
        "profile_delete_account_submit": "Gönder",
        "profile_delete_account_cancel": "Vazgeç",
        "profile_delete_account_pending": "Talebiniz alındı — yönetici inceliyor.",
        "cart_title": "Sepet", "cart_empty_title": "Sepet boş",
        "cart_empty_subtitle": "Katalogdan ürün seçin",
        "cart_total": "Toplam", "cart_submit": "Sipariş ver", "cart_submitting": "Gönderiliyor…",
        "cart_products_section": "Ürünler",
        "cart_order_success_title": "Sipariş alındı",
        "cart_order_success_message": "Firma(lar) sizinle kısa süre içinde iletişime geçecek.",
        "checkout_login_required": "Sipariş vermek için Profil bölümünden giriş yapın",
        "catalog_title": "Katalog", "catalog_search_hint": "Ürün veya firma ara…",
        "likes_title": "Favoriler",
        "likes_login_title": "Favoriler için giriş yapın",
        "likes_login_message": "Beğendiğiniz ürünleri kaydetmek için Profil bölümünden giriş yapın.",
        "likes_empty_title": "Henüz favori ürün yok",
        "likes_empty_message": "Katalogdaki beğendiğiniz ürünü kalp ile işaretleyin.",
        "home_all": "Tümü", "home_gps_detect": "GPS ile belirle",
        "home_camera": "Kamera", "home_gallery": "Galeri",
        "home_collections": "Koleksiyonlar", "home_collections_subtitle": "Her oda için",
        "loc_required_title": "Konum izni gerekli",
        "loc_required_body": "Yakınınızdaki firmaların ürünlerini göstermek için konumunuza ihtiyacımız var. İzin verene kadar ürünler görünmez.",
        "loc_gps_off_title": "Konum kapalı",
        "loc_gps_off_body": "Konum hizmetleri (GPS) kapalı. Çevrenizdeki firmaların ürünlerini görmek için açın.",
        "loc_allow": "İzin ver",
        "loc_open_settings": "Ayarları aç",
        "loc_retry": "Tekrar dene",
        "loc_no_firms": "Çevrenizde aktif firma yok",
        "loc_no_firms_hint": "Şu anda konumunuza hizmet veren firma bulunamadı. Daha sonra tekrar deneyin.",
        "home_featured": "Popüler ürünler", "home_featured_subtitle": "En çok tercih edilen",
        "home_top_products": "En iyi ürünler", "home_back_tooltip": "Ana sayfaya",
        "home_all_products": "Tüm ürünler", "home_nothing_found": "Hiçbir şey bulunamadı.",
        "home_similar_suffix": " benzer ürün bulundu",
        "home_results_suffix": " sonuç", "home_products_suffix": " ürün",
        "home_sort_popular": "Popüler", "home_sort_price_low": "Önce ucuz",
        "home_sort_price_high": "Önce pahalı", "home_sort_name_az": "Ad (A-Z)",
        "home_filters_extra": "Ek filtreler", "home_filter_ar_only": "Sadece AR / 3D olanlar",
        "home_filters_title": "Filtreler",
        "home_viloyat_title": "Bölge", "home_viloyat_all": "Tümü",
        "product_title": "Ürün", "product_variant_field_label": "Varyant (malzeme/renk)",
        "product_dim_width": "Genişlik (m)", "product_dim_height": "Yükseklik (m)",
        "product_dim_depth": "Derinlik (m)", "product_qty_label": "Adet",
        "product_approx_price": "Tahmini fiyat", "product_add_to_cart": "Sepete ekle",
        "product_share_suffix": "\nFurniture Platform uygulamasında görün.",
        "product_try_ar": "AR'da dene",
        "product_3d_ios_note": "3D model mevcut (iOS'ta AR için USDZ gerekir)",
        "product_added_alert_title": "Sepete eklendi",
        "shop_title_fallback": "Mağaza", "shop_view_on_map": "Haritada gör",
        "shop_products": "Ürünler", "shop_no_products": "Henüz ürün yok",
        "shop_reviews_prefix": "Müşteri yorumları (", "shop_reviews_suffix": ")",
        "shop_no_reviews": "Henüz yorum yok", "shop_anonymous_customer": "Müşteri",
        "shop_leave_review": "Yorum bırak", "shop_comment_label": "Yorum (isteğe bağlı)",
        "shop_review_thanks": "Teşekkürler! Yorumunuz kaydedildi.",
        "shop_review_locked": "Yalnızca bu firmadan tamamlanmış bir siparişiniz varsa yorum bırakabilirsiniz.",
    ],
    "ky": [
        "Mahsulot": "Товар",
        "Yetkazish ma'lumotlari": "Жеткирүү маалыматы",
        "Telefon (+998…)": "Телефон (+998…)",
        "Manzil": "Дарек",
        "Izoh (ixtiyoriy)": "Эскертүү (милдеттүү эмес)",
        "Buyurtmani tasdiqlash": "Буйрутманы ырастоо",
        "Buyurtma berish": "Буйрутма берүү",
        "Bekor": "Жокко чыгаруу",
        "Buyurtma qabul qilindi": "Буйрутма кабыл алынды",
        "Kompaniya siz bilan tez orada bog'lanadi.": "Компания жакын арада сиз менен байланышат.",
        "Buyurtma berishdan oldin telefon raqamingizni SMS-kod bilan tasdiqlashingiz kerak.": "Буйрутма берер алдында телефон номурун SMS-код менен ырастаңыз.",
        "Telefonni tasdiqlash": "Телефонду ырастоо",
        "MINIMAL VA FUNKSIONAL": "МИНИМАЛДУУ ЖАНА ФУНКЦИОНАЛДУУ",
        "Uyingizga\nqulaylik va hashamat": "Үйүңүзгө\nыңгайлуулук жана сулуулук",
        "O'zbekistonning eng yaxshi mebel ustalari.\nO'lchamingizga mos dizayn, uyingizga yetkazib berish.": "Өзбекстандын мыкты эмерек уусталары.\nӨлчөмүңүзгө ылайык дизайн, үйгө жеткирүү.",
        "Internet aloqasi yo'q": "Интернет байланышы жок",
        "Hali xabarnoma yo'q.": "Азырынча билдирме жок.",
        "Xabarnomalar": "Билдирмелер",
        "Hammasini o'qilgan qilish": "Баарын окулду деп белгилөө",
        "Hali loyiha yo'q": "Азырынча долбоор жок",
        "Mahsulotlarni AR'da ko'rsatish uchun avval loyiha yarating.": "Товарларды AR'да көрсөтүү үчүн адегенде долбоор түзүңүз.",
        "Loyihalarim": "Долбоорлорум",
        "Yangi loyiha": "Жаңы долбоор",
        "Loyiha nomi": "Долбоордун аталышы",
        "Yaratish": "Түзүү",
        "Hali mahsulot qo'shilmagan": "Азырынча товар кошулган жок",
        "+ Mahsulot qo'shish": "+ Товар кошуу",
        "Rang: joylashtirishda tanlanadi": "Түс: жайгаштырууда тандалат",
        "3D modeli tayyor mahsulot yo'q": "3D модели даяр товар жок",
        "Mahsulot qo'shish": "Товар кошуу",
        "Rangni tanlang": "Түстү тандаңыз",
        "Davom etish": "Улантуу",
        "Bog'langan hisoblar": "Байланышкан аккаунттар",
        "Bog'lash": "Байлоо",
        "Ko'rinish rejimi": "Көрүнүш режими",
        "Rejim": "Режим",
        "Xaridor": "Сатып алуучу",
        "Ish takliflari": "Жумуш сунуштары",
        "Qabul qilish": "Кабыл алуу",
        "Rad etish": "Четке кагуу",
        "Ish tarixi (karyera)": "Жумуш тарыхы (карьера)",
        "hozir": "азыр",
        "So'nggi buyurtmalar": "Акыркы буйрутмалар",
        "Hali buyurtma yo'q": "Азырынча буйрутма жок",
        "va yana %d ta buyurtma": "дагы %d буйрутма",
        "Ishlab chiqarish jarayoni": "Өндүрүш процесси",
        "Ijrochi: %@": "Аткаруучу: %@",
        "Ishlab chiqarish: %d%%": "Өндүрүш: %d%%",
        "Hozir: %@": "Азыр: %@",
        "auth_google": "Google менен кирүү",
        "auth_telegram": "Telegram менен кирүү",
        "dim_title": "Өлчөмдөрү",
        "dim_width": "Туурасы",
        "dim_height": "Бийиктиги",
        "dim_depth": "Тереңдиги",
        "dim_volume": "Көлөмү",
        "company_verified": "Тастыкталган фирма",
        "delivery_title": "Жеткирүү",
        "delivery_free": "Акысыз",
        "delivery_days_suffix": " күн",
        "delivery_agreed": "Жеткирүү шарттары фирма менен макулдашылат",
        "delivery_price_label": "Баасы",
        "delivery_time_label": "Мөөнөт",
        "cart_delivery_note": "Фирма менен макулдашылат",
        "price_from_suffix": " тартып",
        "update_title": "Колдонмону жаңыртыңыз", "update_forced_message": "Бул версия мындан ары колдоого алынбайт. Улантуу үчүн VIDA Market колдонмосун жаңыртыңыз.", "update_available_title": "Жаңы версия бар", "update_button": "Жаңыртуу", "update_later": "Кийинчерээк", "update_retry": "Кайра аракет", "update_recheck": "Кайра текшерүү", "update_latest_version": "Акыркы версия", "update_store_error": "Дүкөндүн шилтемеси ачылган жок",
        "nav_home": "Башкы бет", "nav_catalog": "Каталог", "nav_likes": "Тандалмалар",
        "nav_cart": "Себет", "nav_profile": "Профиль",
        "auth_title": "Кирүү", "auth_phone_hint": "Телефон", "auth_select_country": "Мамлекет",
        "auth_send_code": "Кодду жөнөтүү", "auth_phone_invalid": "Номер туура эмес",
        "auth_code_hint": "Код (6 сан)", "auth_verify": "Кирүү",
        "auth_change_number": "Номерди өзгөртүү", "auth_sms_sent": "SMS жөнөтүлдү",
        "auth_resend": "Кайра жөнөтүү", "auth_profile_title": "Сиздин маалымат",
        "auth_first_name": "Ысым", "auth_last_name": "Фамилия",
        "auth_save": "Сактоо",
        "profile_language": "Тил", "profile_title": "Профиль", "common_logout": "Чыгуу",
        "common_close": "Жабуу", "common_done": "Даяр",
        "product_out_of_stock": "Даяр товар калган жок. Буйрутма берсеңиз, бир аз күтүшүңүз мүмкүн.",
        "gallery_image_error": "Сүрөт жүктөлгөн жок",
        "profile_delete_account_title": "Аккаунтту өчүрүү",
        "profile_delete_account_desc": "Аккаунтуңузду толугу менен өчүрүүнү сурай аласыз — сурооңуз администратор тарабынан каралат.",
        "profile_delete_account_reason_placeholder": "Эмне үчүн аккаунтуңузду өчүргүңүз келет?",
        "profile_delete_account_action": "Суроо жөнөтүү",
        "profile_delete_account_submit": "Жөнөтүү",
        "profile_delete_account_cancel": "Жокко чыгаруу",
        "profile_delete_account_pending": "Сурооңуз кабыл алынды — администратор карап жатат.",
        "cart_title": "Себет", "cart_empty_title": "Себет бош",
        "cart_empty_subtitle": "Каталогдон товар тандаңыз",
        "cart_total": "Жалпы", "cart_submit": "Буйрутма берүү", "cart_submitting": "Жөнөтүлүүдө…",
        "cart_products_section": "Товарлар",
        "cart_order_success_title": "Буйрутма кабыл алынды",
        "cart_order_success_message": "Компания(лар) сиз менен жакында байланышат.",
        "checkout_login_required": "Буйрутма берүү үчүн Профиль бөлүмүнөн кириңиз",
        "catalog_title": "Каталог", "catalog_search_hint": "Товар же компанияны издөө…",
        "likes_title": "Тандалмалар",
        "likes_login_title": "Тандалмалар үчүн кириңиз",
        "likes_login_message": "Жаккан товарларды сактоо үчүн Профиль бөлүмүнөн кириңиз.",
        "likes_empty_title": "Азырынча тандалма товар жок",
        "likes_empty_message": "Каталогдон жаккан товарды жүрөкчө менен белгилеңиз.",
        "home_all": "Баары", "home_gps_detect": "GPS аркылуу аныктоо",
        "home_camera": "Камера", "home_gallery": "Галерея",
        "home_collections": "Коллекциялар", "home_collections_subtitle": "Ар бир бөлмө үчүн",
        "loc_required_title": "Жайгашкан жерге уруксат керек",
        "loc_required_body": "Жакын фирмалардын товарларын көрсөтүү үчүн жайгашкан жериңиз керек. Уруксат бербей турганда товарлар көрүнбөйт.",
        "loc_gps_off_title": "Жайгашуу өчүк",
        "loc_gps_off_body": "Жайгашуу кызматы (GPS) өчүрүлгөн. Аны күйгүзүңүз.",
        "loc_allow": "Уруксат берүү",
        "loc_open_settings": "Жөндөөлөрдү ачуу",
        "loc_retry": "Кайра аракет кылуу",
        "loc_no_firms": "Айланаңызда активдүү фирма жок",
        "loc_no_firms_hint": "Азыркы учурда жайгашкан жериңизге кызмат кылган фирма табылган жок. Кийинчерээк аракет кылыңыз.",
        "home_featured": "Популярдуу товарлар", "home_featured_subtitle": "Эң көп тандалган",
        "home_top_products": "Мыкты товарлар", "home_back_tooltip": "Башкы бетке",
        "home_all_products": "Бардык товарлар", "home_nothing_found": "Эч нерсе табылган жок.",
        "home_similar_suffix": " окшош товар табылды",
        "home_results_suffix": " натыйжа", "home_products_suffix": " товар",
        "home_sort_popular": "Популярдуу", "home_sort_price_low": "Алгач арзан",
        "home_sort_price_high": "Алгач кымбат", "home_sort_name_az": "Аты (A-Z)",
        "home_filters_extra": "Кошумча чыпкалар", "home_filter_ar_only": "Тек AR / 3D бар",
        "home_filters_title": "Чыпкалар",
        "home_viloyat_title": "Облус", "home_viloyat_all": "Баары",
        "product_title": "Товар", "product_variant_field_label": "Вариант (материал/түс)",
        "product_dim_width": "Туурасы (м)", "product_dim_height": "Бийиктиги (м)",
        "product_dim_depth": "Тереңдиги (м)", "product_qty_label": "Саны",
        "product_approx_price": "Болжолдуу баасы", "product_add_to_cart": "Себетке кошуу",
        "product_share_suffix": "\nFurniture Platform колдонмосунда көрүңүз.",
        "product_try_ar": "AR'да сынап көрүү",
        "product_3d_ios_note": "3D модель бар (iOS'то AR үчүн USDZ керек)",
        "product_added_alert_title": "Себетке кошулду",
        "shop_title_fallback": "Дүкөн", "shop_view_on_map": "Картадан көрүү",
        "shop_products": "Товарлар", "shop_no_products": "Азырынча товар жок",
        "shop_reviews_prefix": "Кардарлардын баалары (", "shop_reviews_suffix": ")",
        "shop_no_reviews": "Азырынча баа жок", "shop_anonymous_customer": "Кардар",
        "shop_leave_review": "Баа калтыруу", "shop_comment_label": "Пикир (милдеттүү эмес)",
        "shop_review_thanks": "Рахмат! Баанызис сакталды.",
        "shop_review_locked": "Бул компаниядан аяктаган буйрутмаңыз болсо гана баа калтыра аласыз.",
    ],
    "kk": [
        "Mahsulot": "Тауар",
        "Yetkazish ma'lumotlari": "Жеткізу мәліметтері",
        "Telefon (+998…)": "Телефон (+998…)",
        "Manzil": "Мекенжай",
        "Izoh (ixtiyoriy)": "Түсініктеме (міндетті емес)",
        "Buyurtmani tasdiqlash": "Тапсырысты растау",
        "Buyurtma berish": "Тапсырыс беру",
        "Bekor": "Бас тарту",
        "Buyurtma qabul qilindi": "Тапсырыс қабылданды",
        "Kompaniya siz bilan tez orada bog'lanadi.": "Компания жақын арада сізбен байланысады.",
        "Buyurtma berishdan oldin telefon raqamingizni SMS-kod bilan tasdiqlashingiz kerak.": "Тапсырыс бермес бұрын телефон нөміріңізді SMS-кодпен растаңыз.",
        "Telefonni tasdiqlash": "Телефонды растау",
        "MINIMAL VA FUNKSIONAL": "МИНИМАЛДЫ ЖӘНЕ ФУНКЦИОНАЛДЫ",
        "Uyingizga\nqulaylik va hashamat": "Үйіңізге\nжайлылық пен сән",
        "O'zbekistonning eng yaxshi mebel ustalari.\nO'lchamingizga mos dizayn, uyingizga yetkazib berish.": "Өзбекстанның үздік жиһаз шеберлері.\nӨлшеміңізге сай дизайн, үйге жеткізу.",
        "Internet aloqasi yo'q": "Интернет байланысы жоқ",
        "Hali xabarnoma yo'q.": "Әзірге хабарландыру жоқ.",
        "Xabarnomalar": "Хабарландырулар",
        "Hammasini o'qilgan qilish": "Барлығын оқылды деп белгілеу",
        "Hali loyiha yo'q": "Әзірге жоба жоқ",
        "Mahsulotlarni AR'da ko'rsatish uchun avval loyiha yarating.": "Тауарларды AR-да көрсету үшін алдымен жоба жасаңыз.",
        "Loyihalarim": "Жобаларым",
        "Yangi loyiha": "Жаңа жоба",
        "Loyiha nomi": "Жоба атауы",
        "Yaratish": "Жасау",
        "Hali mahsulot qo'shilmagan": "Әзірге тауар қосылмаған",
        "+ Mahsulot qo'shish": "+ Тауар қосу",
        "Rang: joylashtirishda tanlanadi": "Түс: орналастыру кезінде таңдалады",
        "3D modeli tayyor mahsulot yo'q": "3D моделі дайын тауар жоқ",
        "Mahsulot qo'shish": "Тауар қосу",
        "Rangni tanlang": "Түсті таңдаңыз",
        "Davom etish": "Жалғастыру",
        "Bog'langan hisoblar": "Байланысқан аккаунттар",
        "Bog'lash": "Байланыстыру",
        "Ko'rinish rejimi": "Көрініс режимі",
        "Rejim": "Режим",
        "Xaridor": "Сатып алушы",
        "Ish takliflari": "Жұмыс ұсыныстары",
        "Qabul qilish": "Қабылдау",
        "Rad etish": "Бас тарту",
        "Ish tarixi (karyera)": "Жұмыс тарихы (мансап)",
        "hozir": "қазір",
        "So'nggi buyurtmalar": "Соңғы тапсырыстар",
        "Hali buyurtma yo'q": "Әзірге тапсырыс жоқ",
        "va yana %d ta buyurtma": "және тағы %d тапсырыс",
        "Ishlab chiqarish jarayoni": "Өндіріс барысы",
        "Ijrochi: %@": "Орындаушы: %@",
        "Ishlab chiqarish: %d%%": "Өндіріс: %d%%",
        "Hozir: %@": "Қазір: %@",
        "auth_google": "Google арқылы кіру",
        "auth_telegram": "Telegram арқылы кіру",
        "dim_title": "Өлшемдері",
        "dim_width": "Ені",
        "dim_height": "Биіктігі",
        "dim_depth": "Тереңдігі",
        "dim_volume": "Көлемі",
        "company_verified": "Расталған фирма",
        "delivery_title": "Жеткізу",
        "delivery_free": "Тегін",
        "delivery_days_suffix": " күн",
        "delivery_agreed": "Жеткізу шарттары фирмамен келісіледі",
        "delivery_price_label": "Бағасы",
        "delivery_time_label": "Мерзімі",
        "cart_delivery_note": "Фирмамен келісіледі",
        "price_from_suffix": " бастап",
        "update_title": "Қолданбаны жаңартыңыз", "update_forced_message": "Бұл нұсқа енді қолдау көрсетілмейді. Жалғастыру үшін VIDA Market қолданбасын жаңартыңыз.", "update_available_title": "Жаңа нұсқа қолжетімді", "update_button": "Жаңарту", "update_later": "Кейінірек", "update_retry": "Қайталау", "update_recheck": "Қайта тексеру", "update_latest_version": "Соңғы нұсқа", "update_store_error": "Дүкен сілтемесін ашу мүмкін болмады",
        "nav_home": "Басты бет", "nav_catalog": "Каталог", "nav_likes": "Таңдаулылар",
        "nav_cart": "Себет", "nav_profile": "Профиль",
        "auth_title": "Кіру", "auth_phone_hint": "Телефон", "auth_select_country": "Мемлекет",
        "auth_send_code": "Кодты жіберу", "auth_phone_invalid": "Нөмір қате",
        "auth_code_hint": "Код (6 сан)", "auth_verify": "Кіру",
        "auth_change_number": "Нөмірді өзгерту", "auth_sms_sent": "SMS жіберілді",
        "auth_resend": "Қайта жіберу", "auth_profile_title": "Сіздің деректеріңіз",
        "auth_first_name": "Аты", "auth_last_name": "Тегі",
        "auth_save": "Сақтау",
        "profile_language": "Тіл", "profile_title": "Профиль", "common_logout": "Шығу",
        "common_close": "Жабу", "common_done": "Дайын",
        "product_out_of_stock": "Дайын тауар қалмады. Тапсырыс берсеңіз, біраз күтуіңіз мүмкін.",
        "gallery_image_error": "Сурет жүктелмеді",
        "profile_delete_account_title": "Аккаунтты жою",
        "profile_delete_account_desc": "Аккаунтыңызды толығымен жоюды сұрай аласыз — сұрауыңызды әкімші қарайды.",
        "profile_delete_account_reason_placeholder": "Аккаунтыңызды неге жойғыңыз келеді?",
        "profile_delete_account_action": "Сұрау жіберу",
        "profile_delete_account_submit": "Жіберу",
        "profile_delete_account_cancel": "Бас тарту",
        "profile_delete_account_pending": "Сұрауыңыз қабылданды — әкімші қарап жатыр.",
        "cart_title": "Себет", "cart_empty_title": "Себет бос",
        "cart_empty_subtitle": "Каталогтан тауар таңдаңыз",
        "cart_total": "Барлығы", "cart_submit": "Тапсырыс беру", "cart_submitting": "Жіберілуде…",
        "cart_products_section": "Тауарлар",
        "cart_order_success_title": "Тапсырыс қабылданды",
        "cart_order_success_message": "Компания(лар) сізбен жақын арада байланысады.",
        "checkout_login_required": "Тапсырыс беру үшін Профиль бөлімінен кіріңіз",
        "catalog_title": "Каталог", "catalog_search_hint": "Тауарды немесе компанияны іздеу…",
        "likes_title": "Таңдаулылар",
        "likes_login_title": "Таңдаулылар үшін кіріңіз",
        "likes_login_message": "Ұнаған тауарларды сақтау үшін Профиль бөлімінен кіріңіз.",
        "likes_empty_title": "Әзірше таңдаулы тауар жоқ",
        "likes_empty_message": "Каталогтан ұнаған тауарды жүрекше арқылы белгілеңіз.",
        "home_all": "Барлығы", "home_gps_detect": "GPS арқылы анықтау",
        "home_camera": "Камера", "home_gallery": "Галерея",
        "home_collections": "Коллекциялар", "home_collections_subtitle": "Әр бөлме үшін",
        "loc_required_title": "Орналасқан жерге рұқсат керек",
        "loc_required_body": "Жақын фирмалардың тауарларын көрсету үшін орналасқан жеріңіз қажет. Рұқсат бермейінше тауарлар көрінбейді.",
        "loc_gps_off_title": "Орналасу өшірулі",
        "loc_gps_off_body": "Орналасу қызметі (GPS) өшірулі. Оны қосыңыз.",
        "loc_allow": "Рұқсат беру",
        "loc_open_settings": "Баптауларды ашу",
        "loc_retry": "Қайта көру",
        "loc_no_firms": "Маңайыңызда белсенді фирма жоқ",
        "loc_no_firms_hint": "Қазір орналасқан жеріңізге қызмет көрсететін фирма табылмады. Кейінірек қайталап көріңіз.",
        "home_featured": "Танымал тауарлар", "home_featured_subtitle": "Ең көп таңдалған",
        "home_top_products": "Топ тауарлар", "home_back_tooltip": "Басты бетке",
        "home_all_products": "Барлық тауарлар", "home_nothing_found": "Ештеңе табылмады.",
        "home_similar_suffix": " ұқсас тауар табылды",
        "home_results_suffix": " нәтиже", "home_products_suffix": " тауар",
        "home_sort_popular": "Танымал", "home_sort_price_low": "Алдымен арзан",
        "home_sort_price_high": "Алдымен қымбат", "home_sort_name_az": "Аты (A-Z)",
        "home_filters_extra": "Қосымша сүзгілер", "home_filter_ar_only": "Тек AR / 3D бары",
        "home_filters_title": "Сүзгілер",
        "home_viloyat_title": "Облыс", "home_viloyat_all": "Барлығы",
        "product_title": "Тауар", "product_variant_field_label": "Нұсқа (материал/түс)",
        "product_dim_width": "Ені (м)", "product_dim_height": "Биіктігі (м)",
        "product_dim_depth": "Тереңдігі (м)", "product_qty_label": "Саны",
        "product_approx_price": "Болжамды баға", "product_add_to_cart": "Себетке қосу",
        "product_share_suffix": "\nFurniture Platform қосымшасында көріңіз.",
        "product_try_ar": "AR-да қолданып көру",
        "product_3d_ios_note": "3D модель бар (iOS-та AR үшін USDZ қажет)",
        "product_added_alert_title": "Себетке қосылды",
        "shop_title_fallback": "Дүкен", "shop_view_on_map": "Картадан қарау",
        "shop_products": "Тауарлар", "shop_no_products": "Әзірге тауар жоқ",
        "shop_reviews_prefix": "Клиент пікірлері (", "shop_reviews_suffix": ")",
        "shop_no_reviews": "Әзірге пікір жоқ", "shop_anonymous_customer": "Клиент",
        "shop_leave_review": "Пікір қалдыру", "shop_comment_label": "Пікір (міндетті емес)",
        "shop_review_thanks": "Рақмет! Пікіріңіз сақталды.",
        "shop_review_locked": "Бұл компаниядан аяқталған тапсырысыңыз болса ғана пікір қалдыра аласыз.",
    ],
    "de": [
        "Mahsulot": "Produkt",
        "Yetkazish ma'lumotlari": "Lieferdaten",
        "Telefon (+998…)": "Telefon (+998…)",
        "Manzil": "Adresse",
        "Izoh (ixtiyoriy)": "Notiz (optional)",
        "Buyurtmani tasdiqlash": "Bestellung bestätigen",
        "Buyurtma berish": "Bestellen",
        "Bekor": "Abbrechen",
        "Buyurtma qabul qilindi": "Bestellung erhalten",
        "Kompaniya siz bilan tez orada bog'lanadi.": "Das Unternehmen meldet sich in Kürze bei Ihnen.",
        "Buyurtma berishdan oldin telefon raqamingizni SMS-kod bilan tasdiqlashingiz kerak.": "Bevor Sie bestellen, bestätigen Sie Ihre Telefonnummer per SMS-Code.",
        "Telefonni tasdiqlash": "Telefon bestätigen",
        "MINIMAL VA FUNKSIONAL": "MINIMAL UND FUNKTIONAL",
        "Uyingizga\nqulaylik va hashamat": "Komfort und Luxus\nfür Ihr Zuhause",
        "O'zbekistonning eng yaxshi mebel ustalari.\nO'lchamingizga mos dizayn, uyingizga yetkazib berish.": "Die besten Möbelbauer Usbekistans.\nDesign nach Ihren Maßen, Lieferung nach Hause.",
        "Internet aloqasi yo'q": "Keine Internetverbindung",
        "Hali xabarnoma yo'q.": "Noch keine Benachrichtigungen.",
        "Xabarnomalar": "Benachrichtigungen",
        "Hammasini o'qilgan qilish": "Alle als gelesen markieren",
        "Hali loyiha yo'q": "Noch keine Projekte",
        "Mahsulotlarni AR'da ko'rsatish uchun avval loyiha yarating.": "Erstellen Sie zuerst ein Projekt, um Produkte in AR anzuzeigen.",
        "Loyihalarim": "Meine Projekte",
        "Yangi loyiha": "Neues Projekt",
        "Loyiha nomi": "Projektname",
        "Yaratish": "Erstellen",
        "Hali mahsulot qo'shilmagan": "Noch keine Produkte hinzugefügt",
        "+ Mahsulot qo'shish": "+ Produkt hinzufügen",
        "Rang: joylashtirishda tanlanadi": "Farbe: wird beim Platzieren gewählt",
        "3D modeli tayyor mahsulot yo'q": "Keine Produkte mit fertigem 3D-Modell",
        "Mahsulot qo'shish": "Produkt hinzufügen",
        "Rangni tanlang": "Farbe wählen",
        "Davom etish": "Weiter",
        "Bog'langan hisoblar": "Verknüpfte Konten",
        "Bog'lash": "Verknüpfen",
        "Ko'rinish rejimi": "Ansichtsmodus",
        "Rejim": "Modus",
        "Xaridor": "Kunde",
        "Ish takliflari": "Jobangebote",
        "Qabul qilish": "Annehmen",
        "Rad etish": "Ablehnen",
        "Ish tarixi (karyera)": "Berufsverlauf (Karriere)",
        "hozir": "jetzt",
        "So'nggi buyurtmalar": "Letzte Bestellungen",
        "Hali buyurtma yo'q": "Noch keine Bestellungen",
        "va yana %d ta buyurtma": "und %d weitere Bestellungen",
        "Ishlab chiqarish jarayoni": "Produktionsfortschritt",
        "Ijrochi: %@": "Verantwortlich: %@",
        "Ishlab chiqarish: %d%%": "Produktion: %d%%",
        "Hozir: %@": "Jetzt: %@",
        "auth_google": "Mit Google anmelden",
        "auth_telegram": "Mit Telegram anmelden",
        "dim_title": "Abmessungen",
        "dim_width": "Breite",
        "dim_height": "Höhe",
        "dim_depth": "Tiefe",
        "dim_volume": "Volumen",
        "company_verified": "Verifiziertes Unternehmen",
        "delivery_title": "Lieferung",
        "delivery_free": "Kostenlos",
        "delivery_days_suffix": " Tage",
        "delivery_agreed": "Lieferbedingungen werden mit dem Unternehmen vereinbart",
        "delivery_price_label": "Preis",
        "delivery_time_label": "Dauer",
        "cart_delivery_note": "Wird mit dem Unternehmen vereinbart",
        "price_from_suffix": " ab",
        "update_title": "App aktualisieren", "update_forced_message": "Diese Version wird nicht mehr unterstützt. Bitte aktualisieren Sie VIDA Market, um fortzufahren.", "update_available_title": "Neue Version verfügbar", "update_button": "Aktualisieren", "update_later": "Später", "update_retry": "Erneut versuchen", "update_recheck": "Erneut prüfen", "update_latest_version": "Neueste Version", "update_store_error": "Store-Link konnte nicht geöffnet werden",
        "nav_home": "Start", "nav_catalog": "Katalog", "nav_likes": "Favoriten",
        "nav_cart": "Warenkorb", "nav_profile": "Profil",
        "auth_title": "Anmelden", "auth_phone_hint": "Telefon", "auth_select_country": "Land",
        "auth_send_code": "Code senden", "auth_phone_invalid": "Ungültige Nummer",
        "auth_code_hint": "Code (6 Ziffern)", "auth_verify": "Anmelden",
        "auth_change_number": "Nummer ändern", "auth_sms_sent": "SMS gesendet",
        "auth_resend": "Erneut senden", "auth_profile_title": "Ihre Angaben",
        "auth_first_name": "Vorname", "auth_last_name": "Nachname",
        "auth_save": "Speichern",
        "profile_language": "Sprache", "profile_title": "Profil", "common_logout": "Abmelden",
        "common_close": "Schließen", "common_done": "Fertig",
        "product_out_of_stock": "Fertigware ist nicht vorrätig. Wenn Sie bestellen, müssen Sie eventuell etwas warten.",
        "gallery_image_error": "Bild konnte nicht geladen werden",
        "profile_delete_account_title": "Konto löschen",
        "profile_delete_account_desc": "Sie können die vollständige Löschung Ihres Kontos beantragen — Ihre Anfrage wird von einem Administrator geprüft.",
        "profile_delete_account_reason_placeholder": "Warum möchten Sie Ihr Konto löschen?",
        "profile_delete_account_action": "Anfrage senden",
        "profile_delete_account_submit": "Senden",
        "profile_delete_account_cancel": "Abbrechen",
        "profile_delete_account_pending": "Ihre Anfrage wurde empfangen — ein Administrator prüft sie.",
        "cart_title": "Warenkorb", "cart_empty_title": "Warenkorb ist leer",
        "cart_empty_subtitle": "Wählen Sie ein Produkt aus dem Katalog",
        "cart_total": "Gesamt", "cart_submit": "Bestellen", "cart_submitting": "Wird gesendet…",
        "cart_products_section": "Produkte",
        "cart_order_success_title": "Bestellung erhalten",
        "cart_order_success_message": "Das Unternehmen / die Unternehmen wird / werden sich in Kürze bei Ihnen melden.",
        "checkout_login_required": "Melden Sie sich im Profil an, um zu bestellen",
        "catalog_title": "Katalog", "catalog_search_hint": "Produkt oder Firma suchen…",
        "likes_title": "Favoriten",
        "likes_login_title": "Zum Speichern anmelden",
        "likes_login_message": "Melden Sie sich im Profil an, um gefallene Produkte zu speichern.",
        "likes_empty_title": "Noch keine Favoriten",
        "likes_empty_message": "Markieren Sie ein Produkt im Katalog mit dem Herz-Symbol.",
        "home_all": "Alle", "home_gps_detect": "Per GPS ermitteln",
        "home_camera": "Kamera", "home_gallery": "Galerie",
        "home_collections": "Kollektionen", "home_collections_subtitle": "Für jedes Zimmer",
        "loc_required_title": "Standortberechtigung erforderlich",
        "loc_required_body": "Wir benötigen Ihren Standort, um Produkte von Firmen in Ihrer Nähe zu zeigen. Bis zur Freigabe bleiben Produkte verborgen.",
        "loc_gps_off_title": "Standort ist aus",
        "loc_gps_off_body": "Die Ortungsdienste (GPS) sind ausgeschaltet. Schalten Sie sie ein, um Produkte aus Ihrer Umgebung zu sehen.",
        "loc_allow": "Erlauben",
        "loc_open_settings": "Einstellungen öffnen",
        "loc_retry": "Erneut versuchen",
        "loc_no_firms": "Keine aktive Firma in Ihrer Nähe",
        "loc_no_firms_hint": "Aktuell bedient keine Firma Ihren Standort. Bitte versuchen Sie es später erneut.",
        "home_featured": "Beliebte Produkte", "home_featured_subtitle": "Meistgewählt",
        "home_top_products": "Top-Produkte", "home_back_tooltip": "Zur Startseite",
        "home_all_products": "Alle Produkte", "home_nothing_found": "Nichts gefunden.",
        "home_similar_suffix": " ähnliche Produkte gefunden",
        "home_results_suffix": " Ergebnisse", "home_products_suffix": " Produkte",
        "home_sort_popular": "Beliebt", "home_sort_price_low": "Zuerst günstig",
        "home_sort_price_high": "Zuerst teuer", "home_sort_name_az": "Name (A-Z)",
        "home_filters_extra": "Weitere Filter", "home_filter_ar_only": "Nur mit AR / 3D",
        "home_filters_title": "Filter",
        "home_viloyat_title": "Region", "home_viloyat_all": "Alle",
        "product_title": "Produkt", "product_variant_field_label": "Variante (Material/Farbe)",
        "product_dim_width": "Breite (m)", "product_dim_height": "Höhe (m)",
        "product_dim_depth": "Tiefe (m)", "product_qty_label": "Menge",
        "product_approx_price": "Geschätzter Preis", "product_add_to_cart": "In den Warenkorb",
        "product_share_suffix": "\nSehen Sie es in der Furniture Platform App.",
        "product_try_ar": "In AR ausprobieren",
        "product_3d_ios_note": "3D-Modell verfügbar (AR unter iOS benötigt USDZ)",
        "product_added_alert_title": "Zum Warenkorb hinzugefügt",
        "shop_title_fallback": "Geschäft", "shop_view_on_map": "Auf der Karte ansehen",
        "shop_products": "Produkte", "shop_no_products": "Noch keine Produkte",
        "shop_reviews_prefix": "Kundenbewertungen (", "shop_reviews_suffix": ")",
        "shop_no_reviews": "Noch keine Bewertungen", "shop_anonymous_customer": "Kunde",
        "shop_leave_review": "Bewertung abgeben", "shop_comment_label": "Kommentar (optional)",
        "shop_review_thanks": "Danke! Ihre Bewertung wurde gespeichert.",
        "shop_review_locked": "Sie können erst nach einer abgeschlossenen Bestellung bei dieser Firma eine Bewertung abgeben.",
    ],
    "az": [
        "Mahsulot": "Məhsul",
        "Yetkazish ma'lumotlari": "Çatdırılma məlumatları",
        "Telefon (+998…)": "Telefon (+998…)",
        "Manzil": "Ünvan",
        "Izoh (ixtiyoriy)": "Qeyd (könüllü)",
        "Buyurtmani tasdiqlash": "Sifarişi təsdiqlə",
        "Buyurtma berish": "Sifariş ver",
        "Bekor": "Ləğv et",
        "Buyurtma qabul qilindi": "Sifariş qəbul edildi",
        "Kompaniya siz bilan tez orada bog'lanadi.": "Şirkət tezliklə sizinlə əlaqə saxlayacaq.",
        "Buyurtma berishdan oldin telefon raqamingizni SMS-kod bilan tasdiqlashingiz kerak.": "Sifariş verməzdən əvvəl telefon nömrənizi SMS kodla təsdiqləyin.",
        "Telefonni tasdiqlash": "Telefonu təsdiqlə",
        "MINIMAL VA FUNKSIONAL": "MİNİMAL VƏ FUNKSİONAL",
        "Uyingizga\nqulaylik va hashamat": "Evinizə\nrahatlıq və lüks",
        "O'zbekistonning eng yaxshi mebel ustalari.\nO'lchamingizga mos dizayn, uyingizga yetkazib berish.": "Özbəkistanın ən yaxşı mebel ustaları.\nÖlçünüzə uyğun dizayn, evinizə çatdırılma.",
        "Internet aloqasi yo'q": "İnternet bağlantısı yoxdur",
        "Hali xabarnoma yo'q.": "Hələ bildiriş yoxdur.",
        "Xabarnomalar": "Bildirişlər",
        "Hammasini o'qilgan qilish": "Hamısını oxunmuş et",
        "Hali loyiha yo'q": "Hələ layihə yoxdur",
        "Mahsulotlarni AR'da ko'rsatish uchun avval loyiha yarating.": "Məhsulları AR-da göstərmək üçün əvvəlcə layihə yaradın.",
        "Loyihalarim": "Layihələrim",
        "Yangi loyiha": "Yeni layihə",
        "Loyiha nomi": "Layihə adı",
        "Yaratish": "Yarat",
        "Hali mahsulot qo'shilmagan": "Hələ məhsul əlavə edilməyib",
        "+ Mahsulot qo'shish": "+ Məhsul əlavə et",
        "Rang: joylashtirishda tanlanadi": "Rəng: yerləşdirərkən seçilir",
        "3D modeli tayyor mahsulot yo'q": "Hazır 3D modeli olan məhsul yoxdur",
        "Mahsulot qo'shish": "Məhsul əlavə et",
        "Rangni tanlang": "Rəngi seçin",
        "Davom etish": "Davam et",
        "Bog'langan hisoblar": "Bağlı hesablar",
        "Bog'lash": "Bağla",
        "Ko'rinish rejimi": "Görünüş rejimi",
        "Rejim": "Rejim",
        "Xaridor": "Alıcı",
        "Ish takliflari": "İş təklifləri",
        "Qabul qilish": "Qəbul et",
        "Rad etish": "Rədd et",
        "Ish tarixi (karyera)": "İş tarixçəsi (karyera)",
        "hozir": "indi",
        "So'nggi buyurtmalar": "Son sifarişlər",
        "Hali buyurtma yo'q": "Hələ sifariş yoxdur",
        "va yana %d ta buyurtma": "və daha %d sifariş",
        "Ishlab chiqarish jarayoni": "İstehsal prosesi",
        "Ijrochi: %@": "İcraçı: %@",
        "Ishlab chiqarish: %d%%": "İstehsal: %d%%",
        "Hozir: %@": "İndi: %@",
        "auth_google": "Google ilə daxil ol",
        "auth_telegram": "Telegram ilə daxil ol",
        "dim_title": "Ölçüləri",
        "dim_width": "En",
        "dim_height": "Hündürlük",
        "dim_depth": "Dərinlik",
        "dim_volume": "Həcm",
        "company_verified": "Təsdiqlənmiş firma",
        "delivery_title": "Çatdırılma",
        "delivery_free": "Pulsuz",
        "delivery_days_suffix": " gün",
        "delivery_agreed": "Çatdırılma şərtləri firma ilə razılaşdırılır",
        "delivery_price_label": "Qiymət",
        "delivery_time_label": "Müddət",
        "cart_delivery_note": "Firma ilə razılaşdırılır",
        "price_from_suffix": " dən",
        "update_title": "Tətbiqi yeniləyin", "update_forced_message": "Bu versiya artıq dəstəklənmir. Davam etmək üçün VIDA Market tətbiqini yeniləyin.", "update_available_title": "Yeni versiya mövcuddur", "update_button": "Yenilə", "update_later": "Sonra", "update_retry": "Yenidən cəhd et", "update_recheck": "Yenidən yoxla", "update_latest_version": "Son versiya", "update_store_error": "Mağaza linki açılmadı",
        "nav_home": "Ana səhifə", "nav_catalog": "Kataloq", "nav_likes": "Sevimlilər",
        "nav_cart": "Səbət", "nav_profile": "Profil",
        "auth_title": "Giriş", "auth_phone_hint": "Telefon", "auth_select_country": "Ölkə",
        "auth_send_code": "Kodu göndər", "auth_phone_invalid": "Nömrə yanlışdır",
        "auth_code_hint": "Kod (6 rəqəm)", "auth_verify": "Giriş",
        "auth_change_number": "Nömrəni dəyiş", "auth_sms_sent": "SMS göndərildi",
        "auth_resend": "Yenidən göndər", "auth_profile_title": "Sizin məlumatlarınız",
        "auth_first_name": "Ad", "auth_last_name": "Soyad",
        "auth_save": "Yadda saxla",
        "profile_language": "Dil", "profile_title": "Profil", "common_logout": "Çıxış",
        "common_close": "Bağla", "common_done": "Hazır",
        "product_out_of_stock": "Hazır məhsul qalmayıb. Sifariş versəniz, bir az gözləməli ola bilərsiniz.",
        "gallery_image_error": "Şəkil yüklənmədi",
        "profile_delete_account_title": "Hesabı sil",
        "profile_delete_account_desc": "Hesabınızın tamamilə silinməsini tələb edə bilərsiniz — tələbiniz administrator tərəfindən nəzərdən keçiriləcək.",
        "profile_delete_account_reason_placeholder": "Hesabınızı niyə silmək istəyirsiniz?",
        "profile_delete_account_action": "Tələb göndər",
        "profile_delete_account_submit": "Göndər",
        "profile_delete_account_cancel": "Ləğv et",
        "profile_delete_account_pending": "Tələbiniz qəbul edildi — administrator onu araşdırır.",
        "cart_title": "Səbət", "cart_empty_title": "Səbət boşdur",
        "cart_empty_subtitle": "Katoloqdan məhsul seçin",
        "cart_total": "Cəmi", "cart_submit": "Sifariş ver", "cart_submitting": "Göndərilir…",
        "cart_products_section": "Məhsullar",
        "cart_order_success_title": "Sifariş qəbul edildi",
        "cart_order_success_message": "Şirkət(lər) tezliklə sizinlə əlaqə saxlayacaq.",
        "checkout_login_required": "Sifariş vermək üçün Profil bölməsindən daxil olun",
        "catalog_title": "Kataloq", "catalog_search_hint": "Məhsul və ya firma axtar…",
        "likes_title": "Sevimlilər",
        "likes_login_title": "Sevimlilər üçün daxil olun",
        "likes_login_message": "Bəyəndiyiniz məhsulları saxlamaq üçün Profil bölməsindən daxil olun.",
        "likes_empty_title": "Hələ sevimli məhsul yoxdur",
        "likes_empty_message": "Kataloqdan bəyəndiyiniz məhsulu ürəkcik ilə qeyd edin.",
        "home_all": "Hamısı", "home_gps_detect": "GPS ilə müəyyən et",
        "home_camera": "Kamera", "home_gallery": "Qalereya",
        "home_collections": "Kolleksiyalar", "home_collections_subtitle": "Hər otaq üçün",
        "loc_required_title": "Məkan icazəsi lazımdır",
        "loc_required_body": "Yaxınlığınızdakı firmaların məhsullarını göstərmək üçün məkanınız lazımdır. İcazə verməyincə məhsullar görünmür.",
        "loc_gps_off_title": "Məkan söndürülüb",
        "loc_gps_off_body": "Məkan xidməti (GPS) söndürülüb. Onu yandırın.",
        "loc_allow": "İcazə ver",
        "loc_open_settings": "Ayarları aç",
        "loc_retry": "Yenidən cəhd et",
        "loc_no_firms": "Ətrafınızda aktiv firma yoxdur",
        "loc_no_firms_hint": "Hazırda məkanınıza xidmət göstərən firma tapılmadı. Sonra yenidən cəhd edin.",
        "home_featured": "Populyar məhsullar", "home_featured_subtitle": "Ən çox seçilən",
        "home_top_products": "Top məhsullar", "home_back_tooltip": "Ana səhifəyə",
        "home_all_products": "Bütün məhsullar", "home_nothing_found": "Heç nə tapılmadı.",
        "home_similar_suffix": " oxşar məhsul tapıldı",
        "home_results_suffix": " nəticə", "home_products_suffix": " məhsul",
        "home_sort_popular": "Populyar", "home_sort_price_low": "Əvvəl ucuz",
        "home_sort_price_high": "Əvvəl bahalı", "home_sort_name_az": "Ad (A-Z)",
        "home_filters_extra": "Əlavə filtrlər", "home_filter_ar_only": "Yalnız AR / 3D olanlar",
        "home_filters_title": "Filtrlər",
        "home_viloyat_title": "Region", "home_viloyat_all": "Hamısı",
        "product_title": "Məhsul", "product_variant_field_label": "Variant (material/rəng)",
        "product_dim_width": "En (m)", "product_dim_height": "Hündürlük (m)",
        "product_dim_depth": "Dərinlik (m)", "product_qty_label": "Say",
        "product_approx_price": "Təxmini qiymət", "product_add_to_cart": "Səbətə əlavə et",
        "product_share_suffix": "\nFurniture Platform tətbiqində baxın.",
        "product_try_ar": "AR-da sınayın",
        "product_3d_ios_note": "3D model mövcuddur (iOS-da AR üçün USDZ lazımdır)",
        "product_added_alert_title": "Səbətə əlavə edildi",
        "shop_title_fallback": "Mağaza", "shop_view_on_map": "Xəritədə bax",
        "shop_products": "Məhsullar", "shop_no_products": "Hələ məhsul yoxdur",
        "shop_reviews_prefix": "Müştəri rəyləri (", "shop_reviews_suffix": ")",
        "shop_no_reviews": "Hələ rəy yoxdur", "shop_anonymous_customer": "Müştəri",
        "shop_leave_review": "Rəy bildir", "shop_comment_label": "Şərh (istəyə bağlı)",
        "shop_review_thanks": "Təşəkkürlər! Rəyiniz saxlanıldı.",
        "shop_review_locked": "Yalnız bu firmadan tamamlanmış sifarişiniz varsa rəy bildirə bilərsiniz.",
    ],
]

func translate(_ code: String, _ key: String) -> String {
    stringsTable[code]?[key] ?? stringsTable["uz"]?[key] ?? key
}
