import Foundation

/// Asosiy matnlar lug'ati — 9 til, Flutter'dagi `lib/l10n/strings.dart` va
/// web'dagi `frontend/src/l10n/strings.js` bilan bir xil kalitlar/tarjimalar
/// (barcha platformalarda bir xil so'zlar ishlatiladi). Navigatsiya, kirish
/// (auth), bosh sahifa, sevimlilar, savat va mahsulot sahifasi kabi eng ko'p
/// ko'rinadigan matnlar qamrab olingan.
let appLocales: [(code: String, nativeName: String, flag: String)] = [
    ("uz", "O'zbekcha", "🇺🇿"),
    ("en", "English", "🇬🇧"),
    ("ru", "Русский", "🇷🇺"),
    ("tg", "Тоҷикӣ", "🇹🇯"),
    ("tr", "Türkçe", "🇹🇷"),
    ("ky", "Кыргызча", "🇰🇬"),
    ("kk", "Қазақша", "🇰🇿"),
    ("de", "Deutsch", "🇩🇪"),
    ("az", "Azərbaycan", "🇦🇿"),
]

let defaultLocaleCode = "uz"

private let stringsTable: [String: [String: String]] = [
    "uz": [
        "nav_home": "Bosh sahifa", "nav_catalog": "Katalog", "nav_likes": "Sevimlilar",
        "nav_cart": "Savat", "nav_profile": "Profil",
        "auth_title": "Kirish", "auth_phone_hint": "Telefon", "auth_select_country": "Davlat",
        "auth_send_code": "Kod yuborish", "auth_phone_invalid": "Raqam noto'g'ri",
        "auth_code_hint": "Kod (6 raqam)", "auth_verify": "Kirish",
        "auth_change_number": "Raqamni o'zgartirish", "auth_sms_sent": "SMS yuborildi",
        "auth_resend": "Qayta yuborish", "auth_profile_title": "Ma'lumotlaringiz",
        "auth_first_name": "Ism", "auth_last_name": "Familiya",
        "auth_dob": "Tug'ilgan sana (ixtiyoriy)", "auth_save": "Saqlash",
        "profile_language": "Til", "profile_title": "Profil", "common_logout": "Chiqish",
        "common_close": "Yopish", "common_done": "Tayyor",
        "cart_title": "Savat", "cart_empty_title": "Savat bo'sh",
        "cart_empty_subtitle": "Katalogdan mahsulot tanlang",
        "cart_total": "Jami", "cart_submit": "Buyurtma berish", "cart_submitting": "Yuborilmoqda…",
        "cart_products_section": "Mahsulotlar",
        "cart_order_success_title": "Buyurtma qabul qilindi",
        "cart_order_success_message": "Kompaniya(lar) siz bilan tez orada bog'lanadi.",
        "checkout_login_required": "Buyurtma berish uchun Profil bo'limidan tizimga kiring",
        "catalog_title": "Katalog", "catalog_search_hint": "Mahsulot yoki firma qidirish…",
        "likes_title": "Sevimlilar",
        "likes_login_title": "Sevimlilar uchun kiring",
        "likes_login_message": "Yoqqan mahsulotlaringizni saqlash uchun Profil bo'limidan tizimga kiring.",
        "likes_empty_title": "Hali sevimli mahsulot yo'q",
        "likes_empty_message": "Katalogdan yoqqan mahsulotni yurakcha bilan belgilang.",
        "home_all": "Barchasi", "home_gps_detect": "GPS orqali aniqlash",
        "home_camera": "Kamera", "home_gallery": "Galereya",
        "home_collections": "Kolleksiyalar", "home_collections_subtitle": "Har xona uchun",
        "home_featured": "Ommabop mahsulotlar", "home_featured_subtitle": "Eng ko'p tanlangan",
        "home_top_products": "Top tovarlar", "home_back_tooltip": "Bosh sahifaga",
        "home_all_products": "Barcha mahsulotlar", "home_nothing_found": "Hech narsa topilmadi.",
        "home_similar_suffix": " ta o'xshash mahsulot topildi",
        "home_results_suffix": " ta natija", "home_products_suffix": " ta mahsulot",
        "home_sort_popular": "Ommabop", "home_sort_price_low": "Arzon avval",
        "home_sort_price_high": "Qimmat avval", "home_sort_name_az": "Nomi (A-Z)",
        "home_filters_extra": "Qo'shimcha filtrlar", "home_filter_ar_only": "Faqat AR / 3D mavjud",
        "home_filters_title": "Filtrlar",
        "home_viloyat_title": "Viloyat", "home_viloyat_all": "Barchasi",
        "product_title": "Mahsulot", "product_variant_field_label": "Variant (material/rang)",
        "product_dim_width": "Eni (m)", "product_dim_height": "Bo'yi (m)",
        "product_dim_depth": "Chuquri (m)", "product_qty_label": "Soni",
        "product_approx_price": "Taxminiy narx", "product_add_to_cart": "Savatga qo'shish",
        "product_share_suffix": "\nFurniture Platform ilovasida ko'ring.",
        "product_try_ar": "AR'da sinash",
        "product_3d_ios_note": "3D model mavjud (AR uchun iOS'da USDZ kerak)",
        "product_added_alert_title": "Savatga qo'shildi",
    ],
    "en": [
        "nav_home": "Home", "nav_catalog": "Catalog", "nav_likes": "Favorites",
        "nav_cart": "Cart", "nav_profile": "Profile",
        "auth_title": "Sign in", "auth_phone_hint": "Phone", "auth_select_country": "Country",
        "auth_send_code": "Send code", "auth_phone_invalid": "Invalid number",
        "auth_code_hint": "Code (6 digits)", "auth_verify": "Sign in",
        "auth_change_number": "Change number", "auth_sms_sent": "SMS sent",
        "auth_resend": "Resend", "auth_profile_title": "Your details",
        "auth_first_name": "First name", "auth_last_name": "Last name",
        "auth_dob": "Date of birth (optional)", "auth_save": "Save",
        "profile_language": "Language", "profile_title": "Profile", "common_logout": "Log out",
        "common_close": "Close", "common_done": "Done",
        "cart_title": "Cart", "cart_empty_title": "Cart is empty",
        "cart_empty_subtitle": "Pick something from the catalog",
        "cart_total": "Total", "cart_submit": "Place order", "cart_submitting": "Submitting…",
        "cart_products_section": "Products",
        "cart_order_success_title": "Order received",
        "cart_order_success_message": "The company(ies) will contact you soon.",
        "checkout_login_required": "Sign in from the Profile tab to place an order",
        "catalog_title": "Catalog", "catalog_search_hint": "Search product or company…",
        "likes_title": "Favorites",
        "likes_login_title": "Sign in for favorites",
        "likes_login_message": "Sign in from the Profile tab to save products you like.",
        "likes_empty_title": "No favorites yet",
        "likes_empty_message": "Tap the heart on a product in the catalog to save it here.",
        "home_all": "All", "home_gps_detect": "Detect via GPS",
        "home_camera": "Camera", "home_gallery": "Gallery",
        "home_collections": "Collections", "home_collections_subtitle": "For every room",
        "home_featured": "Popular products", "home_featured_subtitle": "Most chosen",
        "home_top_products": "Top products", "home_back_tooltip": "Back to home",
        "home_all_products": "All products", "home_nothing_found": "Nothing found.",
        "home_similar_suffix": " similar products found",
        "home_results_suffix": " results", "home_products_suffix": " products",
        "home_sort_popular": "Popular", "home_sort_price_low": "Price: low to high",
        "home_sort_price_high": "Price: high to low", "home_sort_name_az": "Name (A-Z)",
        "home_filters_extra": "Additional filters", "home_filter_ar_only": "AR / 3D available only",
        "home_filters_title": "Filters",
        "home_viloyat_title": "Region", "home_viloyat_all": "All",
        "product_title": "Product", "product_variant_field_label": "Variant (material/color)",
        "product_dim_width": "Width (m)", "product_dim_height": "Height (m)",
        "product_dim_depth": "Depth (m)", "product_qty_label": "Quantity",
        "product_approx_price": "Estimated price", "product_add_to_cart": "Add to cart",
        "product_share_suffix": "\nSee it in the Furniture Platform app.",
        "product_try_ar": "Try in AR",
        "product_3d_ios_note": "3D model available (AR on iOS requires USDZ)",
        "product_added_alert_title": "Added to cart",
    ],
    "ru": [
        "nav_home": "Главная", "nav_catalog": "Каталог", "nav_likes": "Избранное",
        "nav_cart": "Корзина", "nav_profile": "Профиль",
        "auth_title": "Вход", "auth_phone_hint": "Телефон", "auth_select_country": "Страна",
        "auth_send_code": "Отправить код", "auth_phone_invalid": "Неверный номер",
        "auth_code_hint": "Код (6 цифр)", "auth_verify": "Войти",
        "auth_change_number": "Изменить номер", "auth_sms_sent": "SMS отправлено",
        "auth_resend": "Отправить снова", "auth_profile_title": "Ваши данные",
        "auth_first_name": "Имя", "auth_last_name": "Фамилия",
        "auth_dob": "Дата рождения (необязательно)", "auth_save": "Сохранить",
        "profile_language": "Язык", "profile_title": "Профиль", "common_logout": "Выйти",
        "common_close": "Закрыть", "common_done": "Готово",
        "cart_title": "Корзина", "cart_empty_title": "Корзина пуста",
        "cart_empty_subtitle": "Выберите товар в каталоге",
        "cart_total": "Итого", "cart_submit": "Оформить заказ", "cart_submitting": "Отправка…",
        "cart_products_section": "Товары",
        "cart_order_success_title": "Заказ принят",
        "cart_order_success_message": "Компания(и) свяжется с вами в ближайшее время.",
        "checkout_login_required": "Войдите в разделе Профиль, чтобы оформить заказ",
        "catalog_title": "Каталог", "catalog_search_hint": "Поиск товара или компании…",
        "likes_title": "Избранное",
        "likes_login_title": "Войдите для избранного",
        "likes_login_message": "Войдите в разделе Профиль, чтобы сохранять понравившиеся товары.",
        "likes_empty_title": "Пока нет избранных товаров",
        "likes_empty_message": "Отметьте понравившийся товар сердечком в каталоге.",
        "home_all": "Все", "home_gps_detect": "Определить по GPS",
        "home_camera": "Камера", "home_gallery": "Галерея",
        "home_collections": "Коллекции", "home_collections_subtitle": "Для каждой комнаты",
        "home_featured": "Популярные товары", "home_featured_subtitle": "Самые выбираемые",
        "home_top_products": "Топ товары", "home_back_tooltip": "На главную",
        "home_all_products": "Все товары", "home_nothing_found": "Ничего не найдено.",
        "home_similar_suffix": " похожих товаров найдено",
        "home_results_suffix": " результатов", "home_products_suffix": " товаров",
        "home_sort_popular": "Популярное", "home_sort_price_low": "Сначала дешёвые",
        "home_sort_price_high": "Сначала дорогие", "home_sort_name_az": "Название (А-Я)",
        "home_filters_extra": "Дополнительные фильтры", "home_filter_ar_only": "Только с AR / 3D",
        "home_filters_title": "Фильтры",
        "home_viloyat_title": "Область", "home_viloyat_all": "Все",
        "product_title": "Товар", "product_variant_field_label": "Вариант (материал/цвет)",
        "product_dim_width": "Ширина (м)", "product_dim_height": "Высота (м)",
        "product_dim_depth": "Глубина (м)", "product_qty_label": "Количество",
        "product_approx_price": "Примерная цена", "product_add_to_cart": "В корзину",
        "product_share_suffix": "\nПосмотрите в приложении Furniture Platform.",
        "product_try_ar": "Примерить в AR",
        "product_3d_ios_note": "3D-модель доступна (для AR на iOS нужен USDZ)",
        "product_added_alert_title": "Добавлено в корзину",
    ],
    "tg": [
        "nav_home": "Саҳифаи асосӣ", "nav_catalog": "Каталог", "nav_likes": "Дӯстдоштаҳо",
        "nav_cart": "Сабад", "nav_profile": "Профил",
        "auth_title": "Воридшавӣ", "auth_phone_hint": "Телефон", "auth_select_country": "Кишвар",
        "auth_send_code": "Фиристодани код", "auth_phone_invalid": "Рақами нодуруст",
        "auth_code_hint": "Код (6 рақам)", "auth_verify": "Ворид шудан",
        "auth_change_number": "Тағйири рақам", "auth_sms_sent": "SMS фиристода шуд",
        "auth_resend": "Дубора фиристодан", "auth_profile_title": "Маълумоти шумо",
        "auth_first_name": "Ном", "auth_last_name": "Насаб",
        "auth_dob": "Санаи таваллуд (ихтиёрӣ)", "auth_save": "Нигоҳ доштан",
        "profile_language": "Забон", "profile_title": "Профил", "common_logout": "Баромадан",
        "common_close": "Пӯшидан", "common_done": "Тайёр",
        "cart_title": "Сабад", "cart_empty_title": "Сабад холист",
        "cart_empty_subtitle": "Аз каталог маҳсулот интихоб кунед",
        "cart_total": "Ҳамагӣ", "cart_submit": "Фармоиш додан", "cart_submitting": "Фиристода истодааст…",
        "cart_products_section": "Маҳсулот",
        "cart_order_success_title": "Фармоиш қабул шуд",
        "cart_order_success_message": "Ширкат(ҳо) ба зудӣ бо шумо тамос мегирад.",
        "checkout_login_required": "Барои фармоиш додан аз бахши Профил ворид шавед",
        "catalog_title": "Каталог", "catalog_search_hint": "Маҳсулот ё ширкатро ҷустуҷӯ кунед…",
        "likes_title": "Дӯстдоштаҳо",
        "likes_login_title": "Барои дӯстдоштаҳо ворид шавед",
        "likes_login_message": "Барои нигоҳ доштани маҳсулоти писандидаатон аз бахши Профил ворид шавед.",
        "likes_empty_title": "Ҳанӯз маҳсулоти дӯстдошта нест",
        "likes_empty_message": "Маҳсулоти писандидаро дар каталог бо дил қайд кунед.",
        "home_all": "Ҳама", "home_gps_detect": "Тавассути GPS муайян кардан",
        "home_camera": "Камера", "home_gallery": "Галерея",
        "home_collections": "Маҷмӯаҳо", "home_collections_subtitle": "Барои ҳар хона",
        "home_featured": "Маҳсулоти маъмул", "home_featured_subtitle": "Бештарин интихобшуда",
        "home_top_products": "Маҳсулоти беҳтарин", "home_back_tooltip": "Ба саҳифаи асосӣ",
        "home_all_products": "Ҳамаи маҳсулот", "home_nothing_found": "Чизе ёфт нашуд.",
        "home_similar_suffix": " маҳсулоти монанд ёфт шуд",
        "home_results_suffix": " натиҷа", "home_products_suffix": " маҳсулот",
        "home_sort_popular": "Маъмул", "home_sort_price_low": "Аввал арзон",
        "home_sort_price_high": "Аввал гарон", "home_sort_name_az": "Ном (А-Я)",
        "home_filters_extra": "Филтрҳои иловагӣ", "home_filter_ar_only": "Танҳо бо AR / 3D",
        "home_filters_title": "Филтрҳо",
        "home_viloyat_title": "Вилоят", "home_viloyat_all": "Ҳама",
        "product_title": "Маҳсулот", "product_variant_field_label": "Вариант (материал/ранг)",
        "product_dim_width": "Паҳно (м)", "product_dim_height": "Баландӣ (м)",
        "product_dim_depth": "Чуқурӣ (м)", "product_qty_label": "Миқдор",
        "product_approx_price": "Нархи тахминӣ", "product_add_to_cart": "Ба сабад илова кардан",
        "product_share_suffix": "\nДар барномаи Furniture Platform бинед.",
        "product_try_ar": "Дар AR санҷидан",
        "product_3d_ios_note": "Модели 3D мавҷуд аст (барои AR дар iOS USDZ лозим аст)",
        "product_added_alert_title": "Ба сабад илова шуд",
    ],
    "tr": [
        "nav_home": "Ana sayfa", "nav_catalog": "Katalog", "nav_likes": "Favoriler",
        "nav_cart": "Sepet", "nav_profile": "Profil",
        "auth_title": "Giriş yap", "auth_phone_hint": "Telefon", "auth_select_country": "Ülke",
        "auth_send_code": "Kodu gönder", "auth_phone_invalid": "Geçersiz numara",
        "auth_code_hint": "Kod (6 haneli)", "auth_verify": "Giriş yap",
        "auth_change_number": "Numarayı değiştir", "auth_sms_sent": "SMS gönderildi",
        "auth_resend": "Tekrar gönder", "auth_profile_title": "Bilgileriniz",
        "auth_first_name": "Ad", "auth_last_name": "Soyad",
        "auth_dob": "Doğum tarihi (isteğe bağlı)", "auth_save": "Kaydet",
        "profile_language": "Dil", "profile_title": "Profil", "common_logout": "Çıkış yap",
        "common_close": "Kapat", "common_done": "Tamam",
        "cart_title": "Sepet", "cart_empty_title": "Sepet boş",
        "cart_empty_subtitle": "Katalogdan ürün seçin",
        "cart_total": "Toplam", "cart_submit": "Sipariş ver", "cart_submitting": "Gönderiliyor…",
        "cart_products_section": "Ürünler",
        "cart_order_success_title": "Sipariş alındı",
        "cart_order_success_message": "Firma(lar) sizinle kısa süre içinde iletişime geçecek.",
        "checkout_login_required": "Sipariş vermek için Profil bölümünden giriş yapın",
        "catalog_title": "Katalog", "catalog_search_hint": "Ürün veya firma ara…",
        "likes_title": "Favoriler",
        "likes_login_title": "Favoriler için giriş yapın",
        "likes_login_message": "Beğendiğiniz ürünleri kaydetmek için Profil bölümünden giriş yapın.",
        "likes_empty_title": "Henüz favori ürün yok",
        "likes_empty_message": "Katalogdaki beğendiğiniz ürünü kalp ile işaretleyin.",
        "home_all": "Tümü", "home_gps_detect": "GPS ile belirle",
        "home_camera": "Kamera", "home_gallery": "Galeri",
        "home_collections": "Koleksiyonlar", "home_collections_subtitle": "Her oda için",
        "home_featured": "Popüler ürünler", "home_featured_subtitle": "En çok tercih edilen",
        "home_top_products": "En iyi ürünler", "home_back_tooltip": "Ana sayfaya",
        "home_all_products": "Tüm ürünler", "home_nothing_found": "Hiçbir şey bulunamadı.",
        "home_similar_suffix": " benzer ürün bulundu",
        "home_results_suffix": " sonuç", "home_products_suffix": " ürün",
        "home_sort_popular": "Popüler", "home_sort_price_low": "Önce ucuz",
        "home_sort_price_high": "Önce pahalı", "home_sort_name_az": "Ad (A-Z)",
        "home_filters_extra": "Ek filtreler", "home_filter_ar_only": "Sadece AR / 3D olanlar",
        "home_filters_title": "Filtreler",
        "home_viloyat_title": "Bölge", "home_viloyat_all": "Tümü",
        "product_title": "Ürün", "product_variant_field_label": "Varyant (malzeme/renk)",
        "product_dim_width": "Genişlik (m)", "product_dim_height": "Yükseklik (m)",
        "product_dim_depth": "Derinlik (m)", "product_qty_label": "Adet",
        "product_approx_price": "Tahmini fiyat", "product_add_to_cart": "Sepete ekle",
        "product_share_suffix": "\nFurniture Platform uygulamasında görün.",
        "product_try_ar": "AR'da dene",
        "product_3d_ios_note": "3D model mevcut (iOS'ta AR için USDZ gerekir)",
        "product_added_alert_title": "Sepete eklendi",
    ],
    "ky": [
        "nav_home": "Башкы бет", "nav_catalog": "Каталог", "nav_likes": "Тандалмалар",
        "nav_cart": "Себет", "nav_profile": "Профиль",
        "auth_title": "Кирүү", "auth_phone_hint": "Телефон", "auth_select_country": "Мамлекет",
        "auth_send_code": "Кодду жөнөтүү", "auth_phone_invalid": "Номер туура эмес",
        "auth_code_hint": "Код (6 сан)", "auth_verify": "Кирүү",
        "auth_change_number": "Номерди өзгөртүү", "auth_sms_sent": "SMS жөнөтүлдү",
        "auth_resend": "Кайра жөнөтүү", "auth_profile_title": "Сиздин маалымат",
        "auth_first_name": "Ысым", "auth_last_name": "Фамилия",
        "auth_dob": "Туулган күнү (милдеттүү эмес)", "auth_save": "Сактоо",
        "profile_language": "Тил", "profile_title": "Профиль", "common_logout": "Чыгуу",
        "common_close": "Жабуу", "common_done": "Даяр",
        "cart_title": "Себет", "cart_empty_title": "Себет бош",
        "cart_empty_subtitle": "Каталогдон товар тандаңыз",
        "cart_total": "Жалпы", "cart_submit": "Буйрутма берүү", "cart_submitting": "Жөнөтүлүүдө…",
        "cart_products_section": "Товарлар",
        "cart_order_success_title": "Буйрутма кабыл алынды",
        "cart_order_success_message": "Компания(лар) сиз менен жакында байланышат.",
        "checkout_login_required": "Буйрутма берүү үчүн Профиль бөлүмүнөн кириңиз",
        "catalog_title": "Каталог", "catalog_search_hint": "Товар же компанияны издөө…",
        "likes_title": "Тандалмалар",
        "likes_login_title": "Тандалмалар үчүн кириңиз",
        "likes_login_message": "Жаккан товарларды сактоо үчүн Профиль бөлүмүнөн кириңиз.",
        "likes_empty_title": "Азырынча тандалма товар жок",
        "likes_empty_message": "Каталогдон жаккан товарды жүрөкчө менен белгилеңиз.",
        "home_all": "Баары", "home_gps_detect": "GPS аркылуу аныктоо",
        "home_camera": "Камера", "home_gallery": "Галерея",
        "home_collections": "Коллекциялар", "home_collections_subtitle": "Ар бир бөлмө үчүн",
        "home_featured": "Популярдуу товарлар", "home_featured_subtitle": "Эң көп тандалган",
        "home_top_products": "Мыкты товарлар", "home_back_tooltip": "Башкы бетке",
        "home_all_products": "Бардык товарлар", "home_nothing_found": "Эч нерсе табылган жок.",
        "home_similar_suffix": " окшош товар табылды",
        "home_results_suffix": " натыйжа", "home_products_suffix": " товар",
        "home_sort_popular": "Популярдуу", "home_sort_price_low": "Алгач арзан",
        "home_sort_price_high": "Алгач кымбат", "home_sort_name_az": "Аты (A-Z)",
        "home_filters_extra": "Кошумча чыпкалар", "home_filter_ar_only": "Тек AR / 3D бар",
        "home_filters_title": "Чыпкалар",
        "home_viloyat_title": "Облус", "home_viloyat_all": "Баары",
        "product_title": "Товар", "product_variant_field_label": "Вариант (материал/түс)",
        "product_dim_width": "Туурасы (м)", "product_dim_height": "Бийиктиги (м)",
        "product_dim_depth": "Тереңдиги (м)", "product_qty_label": "Саны",
        "product_approx_price": "Болжолдуу баасы", "product_add_to_cart": "Себетке кошуу",
        "product_share_suffix": "\nFurniture Platform колдонмосунда көрүңүз.",
        "product_try_ar": "AR'да сынап көрүү",
        "product_3d_ios_note": "3D модель бар (iOS'то AR үчүн USDZ керек)",
        "product_added_alert_title": "Себетке кошулду",
    ],
    "kk": [
        "nav_home": "Басты бет", "nav_catalog": "Каталог", "nav_likes": "Таңдаулылар",
        "nav_cart": "Себет", "nav_profile": "Профиль",
        "auth_title": "Кіру", "auth_phone_hint": "Телефон", "auth_select_country": "Мемлекет",
        "auth_send_code": "Кодты жіберу", "auth_phone_invalid": "Нөмір қате",
        "auth_code_hint": "Код (6 сан)", "auth_verify": "Кіру",
        "auth_change_number": "Нөмірді өзгерту", "auth_sms_sent": "SMS жіберілді",
        "auth_resend": "Қайта жіберу", "auth_profile_title": "Сіздің деректеріңіз",
        "auth_first_name": "Аты", "auth_last_name": "Тегі",
        "auth_dob": "Туған күні (міндетті емес)", "auth_save": "Сақтау",
        "profile_language": "Тіл", "profile_title": "Профиль", "common_logout": "Шығу",
        "common_close": "Жабу", "common_done": "Дайын",
        "cart_title": "Себет", "cart_empty_title": "Себет бос",
        "cart_empty_subtitle": "Каталогтан тауар таңдаңыз",
        "cart_total": "Барлығы", "cart_submit": "Тапсырыс беру", "cart_submitting": "Жіберілуде…",
        "cart_products_section": "Тауарлар",
        "cart_order_success_title": "Тапсырыс қабылданды",
        "cart_order_success_message": "Компания(лар) сізбен жақын арада байланысады.",
        "checkout_login_required": "Тапсырыс беру үшін Профиль бөлімінен кіріңіз",
        "catalog_title": "Каталог", "catalog_search_hint": "Тауарды немесе компанияны іздеу…",
        "likes_title": "Таңдаулылар",
        "likes_login_title": "Таңдаулылар үшін кіріңіз",
        "likes_login_message": "Ұнаған тауарларды сақтау үшін Профиль бөлімінен кіріңіз.",
        "likes_empty_title": "Әзірше таңдаулы тауар жоқ",
        "likes_empty_message": "Каталогтан ұнаған тауарды жүрекше арқылы белгілеңіз.",
        "home_all": "Барлығы", "home_gps_detect": "GPS арқылы анықтау",
        "home_camera": "Камера", "home_gallery": "Галерея",
        "home_collections": "Коллекциялар", "home_collections_subtitle": "Әр бөлме үшін",
        "home_featured": "Танымал тауарлар", "home_featured_subtitle": "Ең көп таңдалған",
        "home_top_products": "Топ тауарлар", "home_back_tooltip": "Басты бетке",
        "home_all_products": "Барлық тауарлар", "home_nothing_found": "Ештеңе табылмады.",
        "home_similar_suffix": " ұқсас тауар табылды",
        "home_results_suffix": " нәтиже", "home_products_suffix": " тауар",
        "home_sort_popular": "Танымал", "home_sort_price_low": "Алдымен арзан",
        "home_sort_price_high": "Алдымен қымбат", "home_sort_name_az": "Аты (A-Z)",
        "home_filters_extra": "Қосымша сүзгілер", "home_filter_ar_only": "Тек AR / 3D бары",
        "home_filters_title": "Сүзгілер",
        "home_viloyat_title": "Облыс", "home_viloyat_all": "Барлығы",
        "product_title": "Тауар", "product_variant_field_label": "Нұсқа (материал/түс)",
        "product_dim_width": "Ені (м)", "product_dim_height": "Биіктігі (м)",
        "product_dim_depth": "Тереңдігі (м)", "product_qty_label": "Саны",
        "product_approx_price": "Болжамды баға", "product_add_to_cart": "Себетке қосу",
        "product_share_suffix": "\nFurniture Platform қосымшасында көріңіз.",
        "product_try_ar": "AR-да қолданып көру",
        "product_3d_ios_note": "3D модель бар (iOS-та AR үшін USDZ қажет)",
        "product_added_alert_title": "Себетке қосылды",
    ],
    "de": [
        "nav_home": "Start", "nav_catalog": "Katalog", "nav_likes": "Favoriten",
        "nav_cart": "Warenkorb", "nav_profile": "Profil",
        "auth_title": "Anmelden", "auth_phone_hint": "Telefon", "auth_select_country": "Land",
        "auth_send_code": "Code senden", "auth_phone_invalid": "Ungültige Nummer",
        "auth_code_hint": "Code (6 Ziffern)", "auth_verify": "Anmelden",
        "auth_change_number": "Nummer ändern", "auth_sms_sent": "SMS gesendet",
        "auth_resend": "Erneut senden", "auth_profile_title": "Ihre Angaben",
        "auth_first_name": "Vorname", "auth_last_name": "Nachname",
        "auth_dob": "Geburtsdatum (optional)", "auth_save": "Speichern",
        "profile_language": "Sprache", "profile_title": "Profil", "common_logout": "Abmelden",
        "common_close": "Schließen", "common_done": "Fertig",
        "cart_title": "Warenkorb", "cart_empty_title": "Warenkorb ist leer",
        "cart_empty_subtitle": "Wählen Sie ein Produkt aus dem Katalog",
        "cart_total": "Gesamt", "cart_submit": "Bestellen", "cart_submitting": "Wird gesendet…",
        "cart_products_section": "Produkte",
        "cart_order_success_title": "Bestellung erhalten",
        "cart_order_success_message": "Das Unternehmen / die Unternehmen wird / werden sich in Kürze bei Ihnen melden.",
        "checkout_login_required": "Melden Sie sich im Profil an, um zu bestellen",
        "catalog_title": "Katalog", "catalog_search_hint": "Produkt oder Firma suchen…",
        "likes_title": "Favoriten",
        "likes_login_title": "Zum Speichern anmelden",
        "likes_login_message": "Melden Sie sich im Profil an, um gefallene Produkte zu speichern.",
        "likes_empty_title": "Noch keine Favoriten",
        "likes_empty_message": "Markieren Sie ein Produkt im Katalog mit dem Herz-Symbol.",
        "home_all": "Alle", "home_gps_detect": "Per GPS ermitteln",
        "home_camera": "Kamera", "home_gallery": "Galerie",
        "home_collections": "Kollektionen", "home_collections_subtitle": "Für jedes Zimmer",
        "home_featured": "Beliebte Produkte", "home_featured_subtitle": "Meistgewählt",
        "home_top_products": "Top-Produkte", "home_back_tooltip": "Zur Startseite",
        "home_all_products": "Alle Produkte", "home_nothing_found": "Nichts gefunden.",
        "home_similar_suffix": " ähnliche Produkte gefunden",
        "home_results_suffix": " Ergebnisse", "home_products_suffix": " Produkte",
        "home_sort_popular": "Beliebt", "home_sort_price_low": "Zuerst günstig",
        "home_sort_price_high": "Zuerst teuer", "home_sort_name_az": "Name (A-Z)",
        "home_filters_extra": "Weitere Filter", "home_filter_ar_only": "Nur mit AR / 3D",
        "home_filters_title": "Filter",
        "home_viloyat_title": "Region", "home_viloyat_all": "Alle",
        "product_title": "Produkt", "product_variant_field_label": "Variante (Material/Farbe)",
        "product_dim_width": "Breite (m)", "product_dim_height": "Höhe (m)",
        "product_dim_depth": "Tiefe (m)", "product_qty_label": "Menge",
        "product_approx_price": "Geschätzter Preis", "product_add_to_cart": "In den Warenkorb",
        "product_share_suffix": "\nSehen Sie es in der Furniture Platform App.",
        "product_try_ar": "In AR ausprobieren",
        "product_3d_ios_note": "3D-Modell verfügbar (AR unter iOS benötigt USDZ)",
        "product_added_alert_title": "Zum Warenkorb hinzugefügt",
    ],
    "az": [
        "nav_home": "Ana səhifə", "nav_catalog": "Kataloq", "nav_likes": "Sevimlilər",
        "nav_cart": "Səbət", "nav_profile": "Profil",
        "auth_title": "Giriş", "auth_phone_hint": "Telefon", "auth_select_country": "Ölkə",
        "auth_send_code": "Kodu göndər", "auth_phone_invalid": "Nömrə yanlışdır",
        "auth_code_hint": "Kod (6 rəqəm)", "auth_verify": "Giriş",
        "auth_change_number": "Nömrəni dəyiş", "auth_sms_sent": "SMS göndərildi",
        "auth_resend": "Yenidən göndər", "auth_profile_title": "Sizin məlumatlarınız",
        "auth_first_name": "Ad", "auth_last_name": "Soyad",
        "auth_dob": "Doğum tarixi (istəyə bağlı)", "auth_save": "Yadda saxla",
        "profile_language": "Dil", "profile_title": "Profil", "common_logout": "Çıxış",
        "common_close": "Bağla", "common_done": "Hazır",
        "cart_title": "Səbət", "cart_empty_title": "Səbət boşdur",
        "cart_empty_subtitle": "Katoloqdan məhsul seçin",
        "cart_total": "Cəmi", "cart_submit": "Sifariş ver", "cart_submitting": "Göndərilir…",
        "cart_products_section": "Məhsullar",
        "cart_order_success_title": "Sifariş qəbul edildi",
        "cart_order_success_message": "Şirkət(lər) tezliklə sizinlə əlaqə saxlayacaq.",
        "checkout_login_required": "Sifariş vermək üçün Profil bölməsindən daxil olun",
        "catalog_title": "Kataloq", "catalog_search_hint": "Məhsul və ya firma axtar…",
        "likes_title": "Sevimlilər",
        "likes_login_title": "Sevimlilər üçün daxil olun",
        "likes_login_message": "Bəyəndiyiniz məhsulları saxlamaq üçün Profil bölməsindən daxil olun.",
        "likes_empty_title": "Hələ sevimli məhsul yoxdur",
        "likes_empty_message": "Kataloqdan bəyəndiyiniz məhsulu ürəkcik ilə qeyd edin.",
        "home_all": "Hamısı", "home_gps_detect": "GPS ilə müəyyən et",
        "home_camera": "Kamera", "home_gallery": "Qalereya",
        "home_collections": "Kolleksiyalar", "home_collections_subtitle": "Hər otaq üçün",
        "home_featured": "Populyar məhsullar", "home_featured_subtitle": "Ən çox seçilən",
        "home_top_products": "Top məhsullar", "home_back_tooltip": "Ana səhifəyə",
        "home_all_products": "Bütün məhsullar", "home_nothing_found": "Heç nə tapılmadı.",
        "home_similar_suffix": " oxşar məhsul tapıldı",
        "home_results_suffix": " nəticə", "home_products_suffix": " məhsul",
        "home_sort_popular": "Populyar", "home_sort_price_low": "Əvvəl ucuz",
        "home_sort_price_high": "Əvvəl bahalı", "home_sort_name_az": "Ad (A-Z)",
        "home_filters_extra": "Əlavə filtrlər", "home_filter_ar_only": "Yalnız AR / 3D olanlar",
        "home_filters_title": "Filtrlər",
        "home_viloyat_title": "Region", "home_viloyat_all": "Hamısı",
        "product_title": "Məhsul", "product_variant_field_label": "Variant (material/rəng)",
        "product_dim_width": "En (m)", "product_dim_height": "Hündürlük (m)",
        "product_dim_depth": "Dərinlik (m)", "product_qty_label": "Say",
        "product_approx_price": "Təxmini qiymət", "product_add_to_cart": "Səbətə əlavə et",
        "product_share_suffix": "\nFurniture Platform tətbiqində baxın.",
        "product_try_ar": "AR-da sınayın",
        "product_3d_ios_note": "3D model mövcuddur (iOS-da AR üçün USDZ lazımdır)",
        "product_added_alert_title": "Səbətə əlavə edildi",
    ],
]

func translate(_ code: String, _ key: String) -> String {
    stringsTable[code]?[key] ?? stringsTable["uz"]?[key] ?? key
}
