# Generated by Django 6.0.7 on 2026-07-22 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0005_employee_multi_positions"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("cutting", "Kesish"),
                            ("edge_processing", "Qirra ishlov"),
                            ("assembly", "Yig'ish"),
                            ("painting", "Bo'yash"),
                            ("quality_control", "Sifat nazorati"),
                            ("installation", "O'rnatish"),
                            ("delivery", "Yetkazib berish"),
                            ("other", "Boshqa"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "Navbatda"),
                            ("in_progress", "Bajarilmoqda"),
                            ("done", "Bajarildi"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_tasks",
                        to="companies.company",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_tasks",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ("status", "deadline", "-created_at"),
            },
        ),
    ]
