# Generated by Django 6.0.7 on 2026-07-22 15:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_employee_base_salary_employee_bonus_per_task"),
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "period",
                    models.DateField(help_text="Oyning 1-kuni, masalan 2026-07-01"),
                ),
                (
                    "base_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("tasks_completed", models.PositiveIntegerField(default=0)),
                (
                    "bonus_per_task",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "bonus_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="companies.company",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="companies.employee",
                    ),
                ),
            ],
            options={
                "ordering": ("-period", "employee"),
                "unique_together": {("employee", "period")},
            },
        ),
    ]
