# Generated by Django 6.0.7 on 2026-07-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0002_payslip"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="workflow_earnings",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
