# Generated by Django 6.0.7 on 2026-08-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0004_migrate_tasks_to_workflow"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductionTask",
        ),
    ]
