# Generated by Django 6.0.7 on 2026-08-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0005_delete_productiontask"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="commission_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payslip",
            name="commission_sales",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="payslip",
            name="hourly_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payslip",
            name="kpi_bonus_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payslip",
            name="kpi_met",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payslip",
            name="manual_hours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="payslip",
            name="pay_type",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
