# Generated by Django 6.0.7 on 2026-08-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "production",
            "0006_payslip_commission_amount_payslip_commission_sales_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payslip",
            name="pay_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fixed", "Faqat oylik"),
                    ("fixed_bonus", "Oylik + vazifa bonusi"),
                    ("commission", "Komissiya (% sotuvdan)"),
                    ("hourly", "Soatbay"),
                ],
                max_length=20,
            ),
        ),
    ]
