# Generated by Django 6.0.7 on 2026-09-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0008_payslippayment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payslip",
            old_name="manual_hours",
            new_name="worked_hours",
        ),
        migrations.AddField(
            model_name="payslip",
            name="completed_tasks_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="pay_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fixed", "Faqat oylik"),
                    ("fixed_bonus", "Oylik + vazifa bonusi"),
                    ("commission", "Komissiya (% sotuvdan)"),
                    ("hourly", "Soatbay"),
                    ("piecework", "Ishbay"),
                ],
                max_length=20,
            ),
        ),
    ]
