# Generated by Django 5.0 on 2025-11-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='material',
        ),
        migrations.AddField(
            model_name='variant',
            name='name',
            field=models.CharField(default='Variant', max_length=100),
            preserve_default=False,
        ),
    ]
