# Generated by Django 5.0 on 2025-11-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_change_variant_material_to_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube yoki video URL', max_length=500, null=True),
        ),
    ]
