# Generated by Django 5.0 on 2025-12-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_add_user_custom_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Yangi'), ('processing', 'Tayyorlanmoqda'), ('completed', 'Yuborilgan'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20),
        ),
    ]
