# Generated by Django 6.0.7 on 2026-07-24 18:51

import apps.projects.models
import common.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0009_branch"),
        ("products", "0004_product_branch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DetailAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "storage_mode",
                    models.CharField(
                        default=common.models.current_storage_mode,
                        editable=False,
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("kafel", "Kafel"),
                            ("oboy", "Oboy"),
                            ("texnika", "Maishiy texnika"),
                            ("mebel_detal", "Mebel detali"),
                            ("boshqa", "Boshqa"),
                        ],
                        default="boshqa",
                        max_length=20,
                    ),
                ),
                (
                    "glb_file",
                    models.FileField(
                        upload_to="projects/detail-assets/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["glb", "gltf"]
                            )
                        ],
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="projects/detail-thumbs/"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail_assets",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ("category", "name"),
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(default="Yangi loyiha", max_length=200)),
                ("is_paid", models.BooleanField(default=False)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "share_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ProjectItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("product", "Mahsulot"), ("detail", "Detal element")],
                        max_length=10,
                    ),
                ),
                (
                    "position",
                    models.JSONField(default=apps.projects.models._default_position),
                ),
                (
                    "rotation",
                    models.JSONField(default=apps.projects.models._default_position),
                ),
                (
                    "scale",
                    models.JSONField(default=apps.projects.models._default_scale),
                ),
                (
                    "detail_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="projects.detailasset",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="products.product",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="projects.project",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="products.variant",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
