# Generated by Django 6.0.7 on 2026-08-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("order_status", "Buyurtma holati"),
                    ("task_assigned", "Vazifa tayinlandi"),
                    ("task_available", "Vazifa boshlashga tayyor"),
                    ("material_suggestion", "Material tavsiyasi"),
                ],
                max_length=20,
            ),
        ),
    ]
