# Generated by Django 6.0.7 on 2026-08-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_pushdevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="pushdevice",
            name="app_version",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="pushdevice",
            name="device_id",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="pushdevice",
            name="device_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="pushdevice",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pushdevice",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pushdevice",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pushdevice",
            name="vcode",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pushdevice",
            name="token",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
