# Generated by Django 6.0.7 on 2026-09-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_pushdevice_app_version_pushdevice_device_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushdevice",
            name="platform",
            field=models.CharField(
                choices=[("android", "Android"), ("ios", "iOS"), ("web", "Web")],
                default="android",
                max_length=10,
            ),
        ),
    ]
