# Generated by Django 6.0.7 on 2026-09-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_alter_pushdevice_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("order_status", "Buyurtma holati"),
                    ("task_assigned", "Vazifa tayinlandi"),
                    ("task_available", "Vazifa boshlashga tayyor"),
                    ("material_suggestion", "Material tavsiyasi"),
                    ("task_pool_open", "Yangi erkin topshiriq"),
                    ("task_application_rejected", "Zayavka rad etildi"),
                    ("attendance_rejected", "Davomat rad etildi"),
                ],
                max_length=30,
            ),
        ),
    ]
