# Generated by Django 5.2.17 on 2026-09-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_alter_notification_notif_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("order_status", "Buyurtma holati"),
                    ("task_assigned", "Vazifa tayinlandi"),
                    ("task_available", "Vazifa boshlashga tayyor"),
                    ("material_suggestion", "Material tavsiyasi"),
                    ("task_pool_open", "Yangi erkin topshiriq"),
                    ("task_application_rejected", "Zayavka rad etildi"),
                    ("attendance_rejected", "Davomat rad etildi"),
                    ("custom_order_location_flag", "Buyurtma joylashuvi shubhali"),
                ],
                max_length=30,
            ),
        ),
    ]
