# Generated by Django 5.2.17 on 2026-09-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0009_alter_notification_notif_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("order_status", "Buyurtma holati"),
                    ("task_assigned", "Vazifa tayinlandi"),
                    ("task_available", "Vazifa boshlashga tayyor"),
                    ("material_suggestion", "Material tavsiyasi"),
                    ("task_pool_open", "Yangi erkin topshiriq"),
                    ("task_application_rejected", "Zayavka rad etildi"),
                    ("attendance_rejected", "Davomat rad etildi"),
                    ("custom_order_location_flag", "Buyurtma joylashuvi shubhali"),
                    ("employee_invited", "Ishga taklif qilindi"),
                    ("employee_invitation_accepted", "Taklif qabul qilindi"),
                    ("employee_invitation_declined", "Taklif rad etildi"),
                    ("account_deletion_requested", "Hisobni o'chirish so'rovi"),
                    ("account_deletion_approved", "Hisobni o'chirish tasdiqlandi"),
                    ("account_deletion_rejected", "Hisobni o'chirish rad etildi"),
                ],
                max_length=30,
            ),
        ),
    ]
