# Generated by Django 5.2.17 on 2026-10-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0011_add_broadcast_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcastnotification",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    (
                        "push_only",
                        "Faqat Push bildirishnoma (Ilova ichida ko'rinmaydi)",
                    ),
                    ("both", "Push + Ilova ichida (Ikkalasida ham ko'rinadi)"),
                    ("inapp_only", "Faqat ilova ichida (Push yuborilmaydi)"),
                ],
                default="push_only",
                help_text="Faqat Push tanlansa — ilovaning 'Bildirishnomalar' sahifasiga tushmaydi, faqat foydalanuvchining telefoniga Push keladi.",
                max_length=20,
                verbose_name="Yetkazish usuli",
            ),
        ),
    ]
