# Generated by Django 6.0.7 on 2026-07-23 09:24

import random
import uuid

from django.db import migrations, models


def backfill_worker_ids(apps, schema_editor):
    User = apps.get_model("users", "User")
    existing = set(User.objects.exclude(worker_id="").values_list("worker_id", flat=True))
    for user in User.objects.filter(worker_id=""):
        while True:
            candidate = "".join(random.choices("0123456789", k=10))
            if candidate not in existing:
                existing.add(candidate)
                break
        user.worker_id = candidate
        user.save(update_fields=["worker_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneOTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_used", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="worker_id",
            field=models.CharField(blank=True, editable=False, max_length=12, default=""),
        ),
        migrations.RunPython(backfill_worker_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="worker_id",
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
