# Generated by Django 6.0.7 on 2026-07-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_phoneotp_user_worker_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="phoneotp",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
