# Generated by Django 6.0.7 on 2026-08-17 22:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_googleaccount"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramLoginSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("telegram_id", models.BigIntegerField(blank=True, null=True)),
                ("telegram_first_name", models.CharField(blank=True, max_length=150)),
                ("telegram_username", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_consumed", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="registration_completed",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="TelegramAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("telegram_id", models.BigIntegerField(editable=False, unique=True)),
                ("telegram_username", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
