# Generated by Django 6.0.7 on 2026-08-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_telegramloginsession_user_registration_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_verified",
            field=models.BooleanField(default=True),
        ),
    ]
