# Generated by Django 6.0.7 on 2026-08-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_telegramloginsession_link_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramloginsession",
            name="client",
            field=models.CharField(
                choices=[
                    ("web", "Veb-sayt"),
                    ("android", "Android ilova"),
                    ("ios", "iOS ilova"),
                ],
                default="web",
                max_length=10,
            ),
        ),
    ]
