# Generated by Django 5.2.17 on 2026-10-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_accountdeletionrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="date_of_birth",
        ),
    ]
