# Generated by Django 6.0.7 on 2026-07-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Kutilmoqda"),
                    ("accepted", "Qabul qilindi"),
                    ("in_production", "Ishlab chiqarilmoqda"),
                    ("ready", "Tayyor"),
                    ("delivering", "Yetkazilmoqda"),
                    ("completed", "Yakunlandi"),
                    ("cancelled", "Bekor qilindi"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
