# Generated by Django 6.0.7 on 2026-08-13 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0013_employee_commission_percent_employee_hourly_rate_and_more"),
        ("orders", "0002_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="sold_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sold_orders",
                to="companies.employee",
            ),
        ),
    ]
