# Generated by Django 6.0.7 on 2026-09-04 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_latitude_order_longitude_alter_order_address_and_more"),
        ("products", "0009_variant_cost_price_variant_discount_ends_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("ready_product", "Tayyor mahsulot"),
                    ("custom_project", "Individual loyiha"),
                ],
                default="ready_product",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="cost_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="is_custom_size",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Kutilmoqda"),
                    ("accepted", "Qabul qilindi"),
                    ("designing", "Loyihalashtirilmoqda"),
                    ("in_production", "Ishlab chiqarilmoqda"),
                    ("ready", "Tayyor"),
                    ("delivering", "Yetkazilmoqda"),
                    ("completed", "Yakunlandi"),
                    ("cancelled", "Bekor qilindi"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_m3_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="products.variant",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variant_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
