# Generated by Django 6.0.7 on 2026-09-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_order_type_orderitem_cost_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="location_flag_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="location_flagged",
            field=models.BooleanField(default=False),
        ),
    ]
