# Generated by Django 5.2.17 on 2026-10-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_location_flag_reason_order_location_flagged"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="original_unit_m3_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
