# Generated by Django 6.0.7 on 2026-07-23 08:38

import common.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0007_review"),
        ("orders", "0002_alter_order_status"),
        ("products", "0003_variant_color_texture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("order_index", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=150)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("usta", "Usta (ishlab chiqarish)"),
                            ("sotuvchi", "Sotuvchi"),
                            ("ornatuvchi", "O'rnatuvchi (montaj)"),
                            ("dizayner", "Dizayner"),
                            ("omborchi", "Omborchi"),
                            ("haydovchi", "Yetkazib beruvchi"),
                            ("menejer", "Menejer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(decimal_places=2, default=1, max_digits=6),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("required_materials", models.TextField(blank=True)),
                (
                    "photo_requirement",
                    models.CharField(
                        choices=[
                            ("required", "Majburiy"),
                            ("optional", "Ixtiyoriy"),
                            ("disabled", "Kerak emas"),
                        ],
                        default="optional",
                        max_length=10,
                    ),
                ),
                (
                    "depends_on",
                    models.ManyToManyField(
                        blank=True,
                        related_name="required_by",
                        to="workflow.workflowstep",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_steps",
                        to="companies.employee",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_steps",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ("order_index", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="WorkflowStepInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("order_index", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=150)),
                ("role", models.CharField(blank=True, max_length=20)),
                (
                    "estimated_hours",
                    models.DecimalField(decimal_places=2, default=1, max_digits=6),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("required_materials", models.TextField(blank=True)),
                (
                    "photo_requirement",
                    models.CharField(
                        choices=[
                            ("required", "Majburiy"),
                            ("optional", "Ixtiyoriy"),
                            ("disabled", "Kerak emas"),
                        ],
                        default="optional",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Navbatda"),
                            ("in_progress", "Bajarilmoqda"),
                            ("completed", "Bajarildi"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "depends_on",
                    models.ManyToManyField(
                        blank=True,
                        related_name="required_by",
                        to="workflow.workflowstepinstance",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_step_instances",
                        to="companies.employee",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_steps",
                        to="orders.order",
                    ),
                ),
                (
                    "template_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instances",
                        to="workflow.workflowstep",
                    ),
                ),
            ],
            options={
                "ordering": ("order_index", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="ProgressUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "storage_mode",
                    models.CharField(
                        default=common.models.current_storage_mode,
                        editable=False,
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="workflow/updates/"
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("is_completion", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="workflow.workflowstepinstance",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
