# Generated by Django 6.0.7 on 2026-08-12 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0011_company_viloyat_delete_branch"),
        ("orders", "0002_alter_order_status"),
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstepinstance",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_instances",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="workflowstepinstance",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflowstepinstance",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="workflowstepinstance",
            name="stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cutting", "Kesish"),
                    ("edge_processing", "Qirra ishlov"),
                    ("assembly", "Yig'ish"),
                    ("painting", "Bo'yash"),
                    ("quality_control", "Sifat nazorati"),
                    ("installation", "O'rnatish"),
                    ("delivery", "Yetkazib berish"),
                    ("other", "Boshqa"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workflowstepinstance",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_steps",
                to="orders.order",
            ),
        ),
    ]
