# Generated by Django 6.0.7 on 2026-08-25 19:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0014_company_facebook_url_company_instagram_url_and_more"),
        ("workflow", "0003_backfill_instance_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="StepApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("approved", "Tasdiqlangan"),
                            ("rejected", "Rad etilgan"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_applications",
                        to="companies.employee",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="workflow.workflowstepinstance",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "unique_together": {("step", "employee")},
            },
        ),
    ]
