# Generated by Django 6.0.7 on 2026-08-28 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0015_tariffplan_company_tariff_plan"),
        ("workflow", "0004_stepapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="quantity",
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name="workflowstepinstance",
            name="quantity",
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.CreateModel(
            name="WorkType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cutting", "Kesish"),
                            ("edge_processing", "Qirra ishlov"),
                            ("assembly", "Yig'ish"),
                            ("painting", "Bo'yash"),
                            ("quality_control", "Sifat nazorati"),
                            ("installation", "O'rnatish"),
                            ("delivery", "Yetkazib berish"),
                            ("other", "Boshqa"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("dona", "Dona"),
                            ("kg", "Kilogramm"),
                            ("m", "Metr"),
                            ("m2", "Kvadrat metr"),
                            ("m3", "Kub metr"),
                            ("litr", "Litr"),
                        ],
                        default="dona",
                        max_length=10,
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "required_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("usta", "Usta (ishlab chiqarish)"),
                            ("sotuvchi", "Sotuvchi"),
                            ("ornatuvchi", "O'rnatuvchi (montaj)"),
                            ("dizayner", "Dizayner"),
                            ("omborchi", "Omborchi"),
                            ("haydovchi", "Yetkazib beruvchi"),
                            ("menejer", "Menejer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_types",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ("stage", "name"),
            },
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="work_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_steps",
                to="workflow.worktype",
            ),
        ),
        migrations.AddField(
            model_name="workflowstepinstance",
            name="work_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="workflow.worktype",
            ),
        ),
    ]
