# Generated by Django 6.0.7 on 2026-08-28 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_materialmovement_workflow_instance_and_more"),
        (
            "workflow",
            "0005_workflowstep_quantity_workflowstepinstance_quantity_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="raw_material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="inventory.material",
            ),
        ),
        migrations.AddField(
            model_name="workflowstepinstance",
            name="material_consumed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workflowstepinstance",
            name="raw_material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="inventory.material",
            ),
        ),
    ]
