# Generated by Django 6.0.7 on 2026-08-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0006_workflowstep_raw_material_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="cut_note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="cut_piece_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="cut_piece_length",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="cut_piece_width",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="workflowstepinstance",
            name="cut_note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="workflowstepinstance",
            name="cut_piece_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflowstepinstance",
            name="cut_piece_length",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="workflowstepinstance",
            name="cut_piece_width",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
