# Generated by Django 6.0.7 on 2026-08-28 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0008_workflowstepinstance_approved_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstepinstance",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflowstepinstance",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workflowstepinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Navbatda"),
                    ("in_progress", "Bajarilmoqda"),
                    ("completed", "Bajarildi"),
                    ("approved", "Tasdiqlangan"),
                    ("cancelled", "Bekor qilindi"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
    ]
