# Generated by Django 6.0.7 on 2026-08-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0009_workflowstepinstance_cancelled_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="comment_requirement",
            field=models.CharField(
                choices=[
                    ("required", "Majburiy"),
                    ("optional", "Ixtiyoriy"),
                    ("disabled", "Kerak emas"),
                ],
                default="optional",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="workflowstepinstance",
            name="comment_requirement",
            field=models.CharField(
                choices=[
                    ("required", "Majburiy"),
                    ("optional", "Ixtiyoriy"),
                    ("disabled", "Kerak emas"),
                ],
                default="optional",
                max_length=10,
            ),
        ),
    ]
