# Generated by Django 6.0.7 on 2026-09-05 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_variant_cost_price_variant_discount_ends_at_and_more"),
        ("workflow", "0010_workflowstep_comment_requirement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="requires_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workflowstepinstance",
            name="planned_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflowstepinstance",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="workflowstepinstance",
            name="requires_approval",
            field=models.BooleanField(default=False),
        ),
    ]
