# Generated by Django 5.2.17 on 2026-09-25 16:41

from django.db import migrations, models


def hide_existing_bazis_work_types(apps, schema_editor):
    """Bazis buyurtma oqimi avval yaratgan ish turlarini ("Kesish: …",
    "Kromkalash: …", "Teshish …") Sozlamalardagi ro'yxatdan yashiramiz."""
    from django.db.models import Q

    WorkType = apps.get_model("workflow", "WorkType")
    WorkType.objects.filter(
        Q(name__startswith="Kesish: ") | Q(name__startswith="Kromkalash: ") | Q(name__startswith="Teshish ")
    ).update(is_auto=True)


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0011_workflowstep_requires_approval_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="worktype",
            name="is_auto",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(hide_existing_bazis_work_types, migrations.RunPython.noop),
    ]
