# Generated by Django 6.0.7 on 2026-07-15 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ("-created_at",), "verbose_name_plural": "companies"},
        ),
    ]
