# Generated by Django 6.0.7 on 2026-07-15 18:16

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_alter_company_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="storage_mode",
            field=models.CharField(
                default=common.models.current_storage_mode,
                editable=False,
                max_length=20,
            ),
        ),
    ]
