# Generated by Django 6.0.7 on 2026-07-15 21:38

from django.db import migrations, models

VALID = {"usta", "sotuvchi", "ornatuvchi", "dizayner", "omborchi", "haydovchi", "menejer"}


def copy_position_forward(apps, schema_editor):
    Employee = apps.get_model("companies", "Employee")
    for emp in Employee.objects.exclude(position=""):
        value = emp.position.strip().lower()
        emp.positions = [value] if value in VALID else ["usta"]
        emp.save(update_fields=["positions"])


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_company_storage_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="positions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(copy_position_forward, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="employee",
            name="position",
        ),
    ]
