# Generated by Django 6.0.7 on 2026-07-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_employee_multi_positions"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="base_salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="employee",
            name="bonus_per_task",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
