# Generated by Django 6.0.7 on 2026-07-23 17:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0008_employee_left_at_employeeinvitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "viloyat",
                    models.CharField(
                        choices=[
                            ("toshkent_shahri", "Toshkent shahri"),
                            ("toshkent_viloyati", "Toshkent viloyati"),
                            ("andijon", "Andijon"),
                            ("buxoro", "Buxoro"),
                            ("fargona", "Farg'ona"),
                            ("jizzax", "Jizzax"),
                            ("xorazm", "Xorazm"),
                            ("namangan", "Namangan"),
                            ("navoiy", "Navoiy"),
                            ("qashqadaryo", "Qashqadaryo"),
                            ("qoraqalpogiston", "Qoraqalpog'iston Respublikasi"),
                            ("samarqand", "Samarqand"),
                            ("sirdaryo", "Sirdaryo"),
                            ("surxondaryo", "Surxondaryo"),
                        ],
                        max_length=30,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=500)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("is_main", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_main", "viloyat"),
            },
        ),
    ]
