# Generated by Django 6.0.7 on 2026-07-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="employment_contract_template",
            field=models.TextField(blank=True),
        ),
    ]
