# Generated by Django 6.0.7 on 2026-08-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0010_company_employment_contract_template"),
        ("inventory", "0005_remove_warehouse_branch"),
        ("products", "0006_remove_product_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="viloyat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("toshkent_shahri", "Toshkent shahri"),
                    ("toshkent_viloyati", "Toshkent viloyati"),
                    ("andijon", "Andijon"),
                    ("buxoro", "Buxoro"),
                    ("fargona", "Farg'ona"),
                    ("jizzax", "Jizzax"),
                    ("xorazm", "Xorazm"),
                    ("namangan", "Namangan"),
                    ("navoiy", "Navoiy"),
                    ("qashqadaryo", "Qashqadaryo"),
                    ("qoraqalpogiston", "Qoraqalpog'iston Respublikasi"),
                    ("samarqand", "Samarqand"),
                    ("sirdaryo", "Sirdaryo"),
                    ("surxondaryo", "Surxondaryo"),
                ],
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="Branch",
        ),
    ]
