# Generated by Django 6.0.7 on 2026-08-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0011_company_viloyat_delete_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="service_radius_km",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
