# Generated by Django 6.0.7 on 2026-08-13 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0012_company_latitude_company_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="commission_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="employee",
            name="hourly_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="employee",
            name="pay_type",
            field=models.CharField(
                choices=[
                    ("fixed", "Faqat oylik"),
                    ("fixed_bonus", "Oylik + vazifa bonusi"),
                    ("commission", "Komissiya (% sotuvdan)"),
                    ("hourly", "Soatbay"),
                ],
                default="fixed_bonus",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employeeinvitation",
            name="commission_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="employeeinvitation",
            name="hourly_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="employeeinvitation",
            name="pay_type",
            field=models.CharField(
                choices=[
                    ("fixed", "Faqat oylik"),
                    ("fixed_bonus", "Oylik + vazifa bonusi"),
                    ("commission", "Komissiya (% sotuvdan)"),
                    ("hourly", "Soatbay"),
                ],
                default="fixed_bonus",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PositionPayStandard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("usta", "Usta (ishlab chiqarish)"),
                            ("sotuvchi", "Sotuvchi"),
                            ("ornatuvchi", "O'rnatuvchi (montaj)"),
                            ("dizayner", "Dizayner"),
                            ("omborchi", "Omborchi"),
                            ("haydovchi", "Yetkazib beruvchi"),
                            ("menejer", "Menejer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pay_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Faqat oylik"),
                            ("fixed_bonus", "Oylik + vazifa bonusi"),
                            ("commission", "Komissiya (% sotuvdan)"),
                            ("hourly", "Soatbay"),
                        ],
                        default="fixed_bonus",
                        max_length=20,
                    ),
                ),
                (
                    "min_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "max_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "default_bonus_per_task",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "default_commission_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "default_hourly_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "kpi_target_tasks_per_month",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "kpi_target_on_time_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "kpi_bonus_multiplier",
                    models.DecimalField(decimal_places=2, default=1, max_digits=4),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pay_standards",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ("position",),
                "unique_together": {("company", "position")},
            },
        ),
    ]
