# Generated by Django 6.0.7 on 2026-08-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0013_employee_commission_percent_employee_hourly_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="facebook_url",
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="company",
            name="instagram_url",
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="company",
            name="telegram_url",
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="company",
            name="website_url",
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
