# Generated by Django 6.0.7 on 2026-08-27 04:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0014_company_facebook_url_company_instagram_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TariffPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "price_per_employee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "price_per_product",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("price_per_employee", "price_per_product"),
            },
        ),
        migrations.AddField(
            model_name="company",
            name="tariff_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies",
                to="companies.tariffplan",
            ),
        ),
    ]
