# Generated by Django 6.0.7 on 2026-09-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0015_tariffplan_company_tariff_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="shift_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="shift_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="pay_type",
            field=models.CharField(
                choices=[
                    ("fixed", "Faqat oylik"),
                    ("fixed_bonus", "Oylik + vazifa bonusi"),
                    ("commission", "Komissiya (% sotuvdan)"),
                    ("hourly", "Soatbay"),
                    ("piecework", "Ishbay"),
                ],
                default="fixed_bonus",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employeeinvitation",
            name="pay_type",
            field=models.CharField(
                choices=[
                    ("fixed", "Faqat oylik"),
                    ("fixed_bonus", "Oylik + vazifa bonusi"),
                    ("commission", "Komissiya (% sotuvdan)"),
                    ("hourly", "Soatbay"),
                    ("piecework", "Ishbay"),
                ],
                default="fixed_bonus",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="positionpaystandard",
            name="pay_type",
            field=models.CharField(
                choices=[
                    ("fixed", "Faqat oylik"),
                    ("fixed_bonus", "Oylik + vazifa bonusi"),
                    ("commission", "Komissiya (% sotuvdan)"),
                    ("hourly", "Soatbay"),
                    ("piecework", "Ishbay"),
                ],
                default="fixed_bonus",
                max_length=20,
            ),
        ),
    ]
