# Generated by Django 6.0.7 on 2026-09-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0016_employee_shift_end_employee_shift_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="lunch_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="lunch_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="work_days",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="employeeinvitation",
            name="lunch_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeeinvitation",
            name="lunch_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeeinvitation",
            name="shift_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeeinvitation",
            name="shift_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeeinvitation",
            name="work_days",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
