# Generated by Django 6.0.7 on 2026-09-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0017_employee_lunch_end_employee_lunch_start_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PositionPayStandard",
        ),
    ]
