# Generated by Django 5.2.17 on 2026-10-08 11:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0018_delete_positionpaystandard"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="company",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CompanyDeliverySettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "delivery_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("delivery_min_days", models.PositiveIntegerField(default=1)),
                ("delivery_max_days", models.PositiveIntegerField(default=3)),
                ("free_delivery", models.BooleanField(default=False)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_settings",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "company delivery settings",
            },
        ),
    ]
