# Generated by Django 5.2.17 on 2026-10-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                (
                    "platform",
                    models.CharField(
                        choices=[("android", "Android"), ("ios", "iOS")], max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("update_required", "Update Required"),
                            ("blocked", "Blocked"),
                        ],
                        default="active",
                        max_length=30,
                    ),
                ),
                ("force_update", models.BooleanField(default=False)),
                ("store_url", models.URLField(blank=True)),
                ("update_message", models.TextField(blank=True)),
                ("release_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("version", "platform"),
                        name="unique_app_version_platform",
                    )
                ],
            },
        ),
    ]
