# Generated by Django 5.2.17 on 2026-10-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_versions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appversion",
            name="platform",
            field=models.CharField(
                choices=[("android", "Android"), ("ios", "iOS"), ("web", "Web")],
                max_length=20,
            ),
        ),
    ]
