# Generated by Django 5.2.17 on 2026-10-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_versions", "0002_alter_appversion_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="appversion",
            name="orders_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
