# Generated by Django 5.2.17 on 2026-10-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_versions", "0003_appversion_orders_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("store_url", models.URLField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
