# Generated by Django 6.0.7 on 2026-09-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesurveymedia",
            name="survey",
        ),
        migrations.AlterField(
            model_name="auditlogentry",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("design", "Dizayn"),
                    ("order_item_cost", "Buyurtma bandi tannarxi"),
                    ("order_status", "Buyurtma holati"),
                ],
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="SiteSurvey",
        ),
        migrations.DeleteModel(
            name="SiteSurveyMedia",
        ),
    ]
