# Generated by Django 5.2.17 on 2026-09-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_orders", "0002_remove_sitesurveymedia_survey_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="design",
            name="bazis_file",
            field=models.FileField(
                blank=True, null=True, upload_to="custom_orders/bazis/"
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="bazis_summary",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
