# Generated by Django 5.2.17 on 2026-09-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0003_design_bazis_file_design_bazis_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='bazis_assignments',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
