# Generated by Django 5.2.17 on 2026-09-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_orders", "0004_design_bazis_assignments"),
    ]

    operations = [
        migrations.AddField(
            model_name="design",
            name="extra_stages",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="design",
            name="material_map",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
