# Generated by Django 6.0.7 on 2026-07-23 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_branch"),
        ("products", "0003_variant_color_texture"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="companies.branch",
            ),
        ),
    ]
