# Generated by Django 6.0.7 on 2026-07-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="name_ru",
        ),
        migrations.RemoveField(
            model_name="product",
            name="video_url",
        ),
    ]
