# Generated by Django 6.0.7 on 2026-08-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_product_name_ru_remove_product_video_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="branch",
        ),
    ]
