# Generated by Django 6.0.7 on 2026-08-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_remove_product_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_signature",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
