# Generated by Django 6.0.7 on 2026-08-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_product_image_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color_tag",
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
