# Generated by Django 5.2.17 on 2026-10-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_variant_cost_price_variant_discount_ends_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="discount_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="variant",
            name="discount_fixed_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="variant",
            name="discount_starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variant",
            name="discount_type",
            field=models.CharField(
                choices=[("percent", "Foiz"), ("fixed", "Qat'iy summa")],
                default="percent",
                max_length=10,
            ),
        ),
    ]
