# Generated by Django 5.2.17 on 2026-10-10 09:54

import apps.products.models
import common.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_variant_discount_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShowcaseProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "storage_mode",
                    models.CharField(
                        default=common.models.current_storage_mode,
                        editable=False,
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.JSONField(
                        default=dict,
                        validators=[apps.products.models._validate_translations],
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        validators=[apps.products.models._validate_translations],
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="showcase/"),
                ),
                (
                    "price_from",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="showcase_products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "showcase product",
                "ordering": ("sort_order", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="ShowcaseImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "storage_mode",
                    models.CharField(
                        default=common.models.current_storage_mode,
                        editable=False,
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="showcase/gallery/")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.showcaseproduct",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order",),
            },
        ),
    ]
