# Generated by Django 5.2.17 on 2026-10-10 11:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_showcase"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_from_render",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="product",
            name="model_dims_cm",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="moderation_note",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="product",
            name="needs_moderation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="render_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="render_status",
            field=models.CharField(
                choices=[
                    ("none", "Render yo'q"),
                    ("pending", "Navbatda"),
                    ("processing", "Render qilinmoqda"),
                    ("ready", "Tayyor"),
                    ("failed", "Xatolik"),
                ],
                db_index=True,
                default="none",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="RenderedImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("variant_name", models.CharField(blank=True, max_length=100)),
                ("variant_slug", models.SlugField(blank=True, max_length=120)),
                ("shot", models.CharField(max_length=10)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("urls", models.JSONField(default=dict)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renders",
                        to="products.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="renders",
                        to="products.variant",
                    ),
                ),
            ],
            options={
                "ordering": ("variant_slug", "sort_order"),
            },
        ),
        migrations.CreateModel(
            name="RenderJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Navbatda"),
                            ("processing", "Jarayonda"),
                            ("done", "Tayyor"),
                            ("failed", "Xatolik"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_s", models.FloatField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="render_jobs",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
