# Generated by Django 5.2.17 on 2026-10-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_rendering"),
    ]

    operations = [
        migrations.AddField(
            model_name="renderjob",
            name="source_name",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
