# Generated by Django 5.2.17 on 2026-10-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_renderjob_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="render_source",
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name="product",
            name="render_status",
            field=models.CharField(
                choices=[
                    ("none", "Rasm yo'q"),
                    ("pending", "Navbatda"),
                    ("processing", "Olinmoqda"),
                    ("ready", "Tayyor"),
                    ("failed", "Xatolik"),
                ],
                db_index=True,
                default="none",
                max_length=12,
            ),
        ),
        migrations.DeleteModel(
            name="RenderJob",
        ),
    ]
